//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Abaseguros.Finanzas.SIAC.DataContracts
{
	/// <summary>
	/// Data Contract Class - PeriodoCollectionDC
	/// </summary>
	[WcfSerialization::CollectionDataContract(Namespace = "http://abaseguros.com")]
	public partial class BusinessUnitCollectionDC : System.Collections.Generic.List<BusinessUnitDC>
	{
	}
}

