//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Abaseguros.Finanzas.SIAC.DataContracts
{
	/// <summary>
	/// Data Contract Class - DiasMesDC
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://abaseguros.com", Name = "DiasMesDC")]
	public partial class DiasMesDC 
	{
		private string d1;
		private string d2;
		private string d3;
		private string d4;
		private string d5;
		private string d6;
		private string d7;
		private string d8;
		private string d9;
		private string d10;
		private string d11;
		private string d12;
		private string d13;
		private string d14;
		private string d15;
		private string d16;
		private string d17;
		private string d18;
		private string d19;
		private string d20;
		private string d21;
		private string d22;
		private string d23;
		private string d24;
		private string d25;
		private string d26;
		private string d27;
		private string d28;
		private string d29;
		private string d30;
		private string d31;
		
		[WcfSerialization::DataMember(Name = "D1", IsRequired = false, Order = 0)]
		public string D1
		{
		  get { return d1; }
		  set { d1 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D2", IsRequired = false, Order = 1)]
		public string D2
		{
		  get { return d2; }
		  set { d2 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D3", IsRequired = false, Order = 2)]
		public string D3
		{
		  get { return d3; }
		  set { d3 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D4", IsRequired = false, Order = 3)]
		public string D4
		{
		  get { return d4; }
		  set { d4 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D5", IsRequired = false, Order = 4)]
		public string D5
		{
		  get { return d5; }
		  set { d5 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D6", IsRequired = false, Order = 5)]
		public string D6
		{
		  get { return d6; }
		  set { d6 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D7", IsRequired = false, Order = 6)]
		public string D7
		{
		  get { return d7; }
		  set { d7 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D8", IsRequired = false, Order = 7)]
		public string D8
		{
		  get { return d8; }
		  set { d8 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D9", IsRequired = false, Order = 8)]
		public string D9
		{
		  get { return d9; }
		  set { d9 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D10", IsRequired = false, Order = 9)]
		public string D10
		{
		  get { return d10; }
		  set { d10 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D11", IsRequired = false, Order = 10)]
		public string D11
		{
		  get { return d11; }
		  set { d11 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D12", IsRequired = false, Order = 11)]
		public string D12
		{
		  get { return d12; }
		  set { d12 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D13", IsRequired = false, Order = 12)]
		public string D13
		{
		  get { return d13; }
		  set { d13 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D14", IsRequired = false, Order = 13)]
		public string D14
		{
		  get { return d14; }
		  set { d14 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D15", IsRequired = false, Order = 14)]
		public string D15
		{
		  get { return d15; }
		  set { d15 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D16", IsRequired = false, Order = 15)]
		public string D16
		{
		  get { return d16; }
		  set { d16 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D17", IsRequired = false, Order = 16)]
		public string D17
		{
		  get { return d17; }
		  set { d17 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D18", IsRequired = false, Order = 17)]
		public string D18
		{
		  get { return d18; }
		  set { d18 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D19", IsRequired = false, Order = 18)]
		public string D19
		{
		  get { return d19; }
		  set { d19 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D20", IsRequired = false, Order = 19)]
		public string D20
		{
		  get { return d20; }
		  set { d20 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D21", IsRequired = false, Order = 20)]
		public string D21
		{
		  get { return d21; }
		  set { d21 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D22", IsRequired = false, Order = 21)]
		public string D22
		{
		  get { return d22; }
		  set { d22 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D23", IsRequired = false, Order = 22)]
		public string D23
		{
		  get { return d23; }
		  set { d23 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D24", IsRequired = false, Order = 23)]
		public string D24
		{
		  get { return d24; }
		  set { d24 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D25", IsRequired = false, Order = 24)]
		public string D25
		{
		  get { return d25; }
		  set { d25 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D26", IsRequired = false, Order = 25)]
		public string D26
		{
		  get { return d26; }
		  set { d26 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D27", IsRequired = false, Order = 26)]
		public string D27
		{
		  get { return d27; }
		  set { d27 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D28", IsRequired = false, Order = 27)]
		public string D28
		{
		  get { return d28; }
		  set { d28 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D29", IsRequired = false, Order = 28)]
		public string D29
		{
		  get { return d29; }
		  set { d29 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D30", IsRequired = false, Order = 29)]
		public string D30
		{
		  get { return d30; }
		  set { d30 = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "D31", IsRequired = false, Order = 30)]
		public string D31
		{
		  get { return d31; }
		  set { d31 = value; }
		}				
	}
}

