//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Abaseguros.Finanzas.SIAC.DataContracts
{
	/// <summary>
	/// Data Contract Class - HistorialRODC
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://abaseguros.com", Name = "HistorialRODC")]
	public partial class HistorialRODC 
	{
		private int idRutasArchivosField;
		private string tipoArchivo;
		private string nombre;
		private string plaza;
		private string sistema;
		private string usuario;
		private System.Nullable<System.DateTime> fechaModificacion;
		private System.Nullable<int> estatus;
		
		[WcfSerialization::DataMember(Name = "idRutasArchivos", IsRequired = false, Order = 0)]
		public int idRutasArchivos
		{
		  get { return idRutasArchivosField; }
		  set { idRutasArchivosField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "TipoArchivo", IsRequired = false, Order = 1)]
		public string TipoArchivo
		{
		  get { return tipoArchivo; }
		  set { tipoArchivo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Nombre", IsRequired = false, Order = 2)]
		public string Nombre
		{
		  get { return nombre; }
		  set { nombre = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Plaza", IsRequired = false, Order = 3)]
		public string Plaza
		{
		  get { return plaza; }
		  set { plaza = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Sistema", IsRequired = false, Order = 4)]
		public string Sistema
		{
		  get { return sistema; }
		  set { sistema = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Usuario", IsRequired = false, Order = 5)]
		public string Usuario
		{
		  get { return usuario; }
		  set { usuario = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaModificacion", IsRequired = false, Order = 6)]
		public System.Nullable<System.DateTime> FechaModificacion
		{
		  get { return fechaModificacion; }
		  set { fechaModificacion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estatus", IsRequired = false, Order = 7)]
		public System.Nullable<int> Estatus
		{
		  get { return estatus; }
		  set { estatus = value; }
		}				
	}
}

