//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Abaseguros.Finanzas.SIAC.DataContracts
{
	/// <summary>
	/// Data Contract Class - InsertaParametroReporteDC
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://abaseguros.com", Name = "InsertaParametroReporteDC")]
	public partial class InsertaParametroReporteDC 
	{
		private string idRutaArchivosField;
		private System.Nullable<int> businessUnit;
		private System.Nullable<int> idSistemaField;
		private System.Nullable<int> idPlazaField;
		private System.DateTime fechaValidacion;
		private string login;
		
		[WcfSerialization::DataMember(Name = "idRutaArchivos", IsRequired = false, Order = 0)]
		public string idRutaArchivos
		{
		  get { return idRutaArchivosField; }
		  set { idRutaArchivosField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "BusinessUnit", IsRequired = false, Order = 1)]
		public System.Nullable<int> BusinessUnit
		{
		  get { return businessUnit; }
		  set { businessUnit = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "idSistema", IsRequired = false, Order = 2)]
		public System.Nullable<int> idSistema
		{
		  get { return idSistemaField; }
		  set { idSistemaField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "idPlaza", IsRequired = false, Order = 3)]
		public System.Nullable<int> idPlaza
		{
		  get { return idPlazaField; }
		  set { idPlazaField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaValidacion", IsRequired = false, Order = 4)]
		public System.DateTime FechaValidacion
		{
		  get { return fechaValidacion; }
		  set { fechaValidacion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Login", IsRequired = false, Order = 5)]
		public string Login
		{
		  get { return login; }
		  set { login = value; }
		}				
	}
}

