//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Abaseguros.Finanzas.SIAC.DataContracts
{
	/// <summary>
	/// Data Contract Class - ObtieneBitacoraDC
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://abaseguros.com", Name = "ObtieneBitacoraDC")]
	public partial class ObtieneBitacoraDC 
	{
		private double idMensajeField;
		private System.DateTime fechaModificacion;
		private string mensaje;
		private string estado;
		private System.Nullable<int> idValidacionField;
		
		[WcfSerialization::DataMember(Name = "idMensaje", IsRequired = false, Order = 0)]
		public double idMensaje
		{
		  get { return idMensajeField; }
		  set { idMensajeField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaModificacion", IsRequired = false, Order = 1)]
		public System.DateTime FechaModificacion
		{
		  get { return fechaModificacion; }
		  set { fechaModificacion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Mensaje", IsRequired = false, Order = 2)]
		public string Mensaje
		{
		  get { return mensaje; }
		  set { mensaje = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estado", IsRequired = false, Order = 3)]
		public string Estado
		{
		  get { return estado; }
		  set { estado = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "idValidacion", IsRequired = false, Order = 4)]
		public System.Nullable<int> idValidacion
		{
		  get { return idValidacionField; }
		  set { idValidacionField = value; }
		}				
	}
}

