//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Abaseguros.Finanzas.SIAC.DataContracts
{
	/// <summary>
	/// Data Contract Class - PeriodoDC
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://abaseguros.com", Name = "PeriodoDC")]
	public partial class PeriodoDC 
	{
		private int periodo;
		private int estado;
		private System.DateTime fechaModificacion;
		private string usuario;
		private int businessUnit;
		
		[WcfSerialization::DataMember(Name = "Periodo", IsRequired = false, Order = 0)]
		public int Periodo
		{
		  get { return periodo; }
		  set { periodo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estado", IsRequired = false, Order = 1)]
		public int Estado
		{
		  get { return estado; }
		  set { estado = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaModificacion", IsRequired = false, Order = 2)]
		public System.DateTime FechaModificacion
		{
		  get { return fechaModificacion; }
		  set { fechaModificacion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Usuario", IsRequired = false, Order = 3)]
		public string Usuario
		{
		  get { return usuario; }
		  set { usuario = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "BusinessUnit", IsRequired = false, Order = 4)]
		public int BusinessUnit
		{
		  get { return businessUnit; }
		  set { businessUnit = value; }
		}				
	}
}

