//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Abaseguros.Finanzas.SIAC.DataContracts
{
	/// <summary>
	/// Data Contract Class - PlazaDC
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://abaseguros.com", Name = "PlazaDC")]
	public partial class PlazaDC 
	{
		private int idPlaza;
		private string descripcion;
		
		[WcfSerialization::DataMember(Name = "IdPlaza", IsRequired = false, Order = 0)]
		public int IdPlaza
		{
		  get { return idPlaza; }
		  set { idPlaza = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Descripcion", IsRequired = false, Order = 1)]
		public string Descripcion
		{
		  get { return descripcion; }
		  set { descripcion = value; }
		}				
	}
}

