//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Abaseguros.Finanzas.SIAC.DataContracts
{
	/// <summary>
	/// Data Contract Class - ReporteCalendarioPCWDC
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://abaseguros.com", Name = "ReporteCalendarioPCWDC")]
	public partial class ReporteCalendarioPCWDC 
	{
		private string compania;
		private string archivo;
		private System.DateTime fechaInicio;
		private System.DateTime fechaFin;
		private int semana;
		private int periodoId;
		
		[WcfSerialization::DataMember(Name = "Compania", IsRequired = false, Order = 0)]
		public string Compania
		{
		  get { return compania; }
		  set { compania = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Archivo", IsRequired = false, Order = 1)]
		public string Archivo
		{
		  get { return archivo; }
		  set { archivo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaInicio", IsRequired = false, Order = 2)]
		public System.DateTime FechaInicio
		{
		  get { return fechaInicio; }
		  set { fechaInicio = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaFin", IsRequired = false, Order = 3)]
		public System.DateTime FechaFin
		{
		  get { return fechaFin; }
		  set { fechaFin = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Semana", IsRequired = false, Order = 4)]
		public int Semana
		{
		  get { return semana; }
		  set { semana = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "PeriodoId", IsRequired = false, Order = 5)]
		public int PeriodoId
		{
		  get { return periodoId; }
		  set { periodoId = value; }
		}				
	}
}

