//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Abaseguros.Finanzas.SIAC.DataContracts
{
	/// <summary>
	/// Data Contract Class - ReportePosValidacionMensajesDC
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://abaseguros.com", Name = "ReportePosValidacionMensajesDC")]
	public partial class ReportePosValidacionMensajesDC 
	{
		private int reportePosValidacionMensajesId;
		private int reportePosValidacionId;
		private System.DateTime fechaModificacion;
		private int estatus;
		private string mensaje;
		private string origenEstatus;
		
		[WcfSerialization::DataMember(Name = "ReportePosValidacionMensajesId", IsRequired = false, Order = 0)]
		public int ReportePosValidacionMensajesId
		{
		  get { return reportePosValidacionMensajesId; }
		  set { reportePosValidacionMensajesId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ReportePosValidacionId", IsRequired = false, Order = 1)]
		public int ReportePosValidacionId
		{
		  get { return reportePosValidacionId; }
		  set { reportePosValidacionId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaModificacion", IsRequired = false, Order = 2)]
		public System.DateTime FechaModificacion
		{
		  get { return fechaModificacion; }
		  set { fechaModificacion = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estatus", IsRequired = false, Order = 3)]
		public int Estatus
		{
		  get { return estatus; }
		  set { estatus = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Mensaje", IsRequired = false, Order = 4)]
		public string Mensaje
		{
		  get { return mensaje; }
		  set { mensaje = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "OrigenEstatus", IsRequired = false, Order = 5)]
		public string OrigenEstatus
		{
		  get { return origenEstatus; }
		  set { origenEstatus = value; }
		}				
	}
}

