//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Abaseguros.Finanzas.SIAC.DataContracts
{
	/// <summary>
	/// Data Contract Class - ReporteMonitoreoPSDC
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://abaseguros.com", Name = "ReporteMonitoreoPSDC")]
	public partial class ReporteMonitoreoPSDC 
	{
		private string businessUnit;
		private string sistema;
		private int procesoId;
		private string journalId;
		private System.DateTime fechaContable;
		private string plaza;
		private string estado;
		private string archivo;
		private string ledger;
		
		[WcfSerialization::DataMember(Name = "BusinessUnit", IsRequired = false, Order = 0)]
		public string BusinessUnit
		{
		  get { return businessUnit; }
		  set { businessUnit = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Sistema", IsRequired = false, Order = 1)]
		public string Sistema
		{
		  get { return sistema; }
		  set { sistema = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ProcesoId", IsRequired = false, Order = 2)]
		public int ProcesoId
		{
		  get { return procesoId; }
		  set { procesoId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "JournalId", IsRequired = false, Order = 3)]
		public string JournalId
		{
		  get { return journalId; }
		  set { journalId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaContable", IsRequired = false, Order = 4)]
		public System.DateTime FechaContable
		{
		  get { return fechaContable; }
		  set { fechaContable = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Plaza", IsRequired = false, Order = 5)]
		public string Plaza
		{
		  get { return plaza; }
		  set { plaza = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estado", IsRequired = false, Order = 6)]
		public string Estado
		{
		  get { return estado; }
		  set { estado = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Archivo", IsRequired = false, Order = 7)]
		public string Archivo
		{
		  get { return archivo; }
		  set { archivo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Ledger", IsRequired = false, Order = 8)]
		public string Ledger
		{
		  get { return ledger; }
		  set { ledger = value; }
		}				
	}
}

