//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Abaseguros.Finanzas.SIAC.DataContracts
{
	/// <summary>
	/// Data Contract Class - ReporteMonitoreoPCWDC
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://abaseguros.com", Name = "ReporteMonitoreoPCWDC")]
	public partial class ReporteMonitoreoPCWDC 
	{
		private string compania;
		private string archivo;
		private int procesoId;
		private int voucherABA;
		private System.DateTime fechaContable;
		private string sistema;
		private string plaza;
		private string estado;
		
		[WcfSerialization::DataMember(Name = "Compania", IsRequired = false, Order = 0)]
		public string Compania
		{
		  get { return compania; }
		  set { compania = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Archivo", IsRequired = false, Order = 1)]
		public string Archivo
		{
		  get { return archivo; }
		  set { archivo = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ProcesoId", IsRequired = false, Order = 2)]
		public int ProcesoId
		{
		  get { return procesoId; }
		  set { procesoId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "VoucherABA", IsRequired = false, Order = 3)]
		public int VoucherABA
		{
		  get { return voucherABA; }
		  set { voucherABA = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaContable", IsRequired = false, Order = 4)]
		public System.DateTime FechaContable
		{
		  get { return fechaContable; }
		  set { fechaContable = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Sistema", IsRequired = false, Order = 5)]
		public string Sistema
		{
		  get { return sistema; }
		  set { sistema = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Plaza", IsRequired = false, Order = 6)]
		public string Plaza
		{
		  get { return plaza; }
		  set { plaza = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estado", IsRequired = false, Order = 7)]
		public string Estado
		{
		  get { return estado; }
		  set { estado = value; }
		}				
	}
}

