//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Abaseguros.Finanzas.SIAC.DataContracts
{
	/// <summary>
	/// Data Contract Class - Request_BU_Sistema_Plaza_PeriodoDC
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://abaseguros.com", Name = "Request_BU_Sistema_Plaza_PeriodoDC")]
	public partial class Request_BU_Sistema_Plaza_PeriodoDC 
	{
		private int businessUnit;
		private int idSistemaField;
		private int idPlazaField;
		private int periodoId;
		
		[WcfSerialization::DataMember(Name = "BusinessUnit", IsRequired = false, Order = 0)]
		public int BusinessUnit
		{
		  get { return businessUnit; }
		  set { businessUnit = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "idSistema", IsRequired = false, Order = 1)]
		public int idSistema
		{
		  get { return idSistemaField; }
		  set { idSistemaField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "idPlaza", IsRequired = false, Order = 2)]
		public int idPlaza
		{
		  get { return idPlazaField; }
		  set { idPlazaField = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "PeriodoId", IsRequired = false, Order = 3)]
		public int PeriodoId
		{
		  get { return periodoId; }
		  set { periodoId = value; }
		}				
	}
}

