//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Abaseguros.Finanzas.SIAC.DataContracts
{
	/// <summary>
	/// Data Contract Class - ResultadosPosValidacionDC
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://abaseguros.com", Name = "ResultadosPosValidacionDC")]
	public partial class ResultadosPosValidacionDC 
	{
		private string moneda;
		private double montoStagging;
		private double montoSistema;
		private string cuentaAlterna;
		private double tolerancia;
		private string estado;
		private double diferenciaSisSta;
		private string comentarios;
		private int validacionId;
		private double montoCrawley;
		private double montoPS;
		private double diferenciaStaCra;
		private double diferenciaCraPs;
		private double diferenciaSisPs;
		private int estadoValidacion;
		
		[WcfSerialization::DataMember(Name = "Moneda", IsRequired = false, Order = 0)]
		public string Moneda
		{
		  get { return moneda; }
		  set { moneda = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "MontoStagging", IsRequired = false, Order = 1)]
		public double MontoStagging
		{
		  get { return montoStagging; }
		  set { montoStagging = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "MontoSistema", IsRequired = false, Order = 2)]
		public double MontoSistema
		{
		  get { return montoSistema; }
		  set { montoSistema = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CuentaAlterna", IsRequired = false, Order = 3)]
		public string CuentaAlterna
		{
		  get { return cuentaAlterna; }
		  set { cuentaAlterna = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Tolerancia", IsRequired = false, Order = 4)]
		public double Tolerancia
		{
		  get { return tolerancia; }
		  set { tolerancia = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estado", IsRequired = false, Order = 5)]
		public string Estado
		{
		  get { return estado; }
		  set { estado = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "DiferenciaSisSta", IsRequired = false, Order = 6)]
		public double DiferenciaSisSta
		{
		  get { return diferenciaSisSta; }
		  set { diferenciaSisSta = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Comentarios", IsRequired = false, Order = 7)]
		public string Comentarios
		{
		  get { return comentarios; }
		  set { comentarios = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ValidacionId", IsRequired = false, Order = 8)]
		public int ValidacionId
		{
		  get { return validacionId; }
		  set { validacionId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "MontoCrawley", IsRequired = false, Order = 9)]
		public double MontoCrawley
		{
		  get { return montoCrawley; }
		  set { montoCrawley = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "MontoPS", IsRequired = false, Order = 10)]
		public double MontoPS
		{
		  get { return montoPS; }
		  set { montoPS = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "DiferenciaStaCra", IsRequired = false, Order = 11)]
		public double DiferenciaStaCra
		{
		  get { return diferenciaStaCra; }
		  set { diferenciaStaCra = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "DiferenciaCraPs", IsRequired = false, Order = 12)]
		public double DiferenciaCraPs
		{
		  get { return diferenciaCraPs; }
		  set { diferenciaCraPs = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "DiferenciaSisPs", IsRequired = false, Order = 13)]
		public double DiferenciaSisPs
		{
		  get { return diferenciaSisPs; }
		  set { diferenciaSisPs = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "EstadoValidacion", IsRequired = false, Order = 14)]
		public int EstadoValidacion
		{
		  get { return estadoValidacion; }
		  set { estadoValidacion = value; }
		}				
	}
}

