//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Abaseguros.Finanzas.SIAC.DataContracts
{
	/// <summary>
	/// Data Contract Class - ResultadosPreValidacionDC
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://abaseguros.com", Name = "ResultadosPreValidacionDC")]
	public partial class ResultadosPreValidacionDC 
	{
		private System.DateTime fechaContable;
		private string moneda;
		private double montoContabilidad;
		private double montoSistema;
		private string cuentaAlterna;
		private double tolerancia;
		private string estado;
		private double diferencia;
		private string comentarios;
		private int validacionId;
		private int registroId;
		private int habilitaAplicaRevision;
		
		[WcfSerialization::DataMember(Name = "FechaContable", IsRequired = false, Order = 0)]
		public System.DateTime FechaContable
		{
		  get { return fechaContable; }
		  set { fechaContable = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Moneda", IsRequired = false, Order = 1)]
		public string Moneda
		{
		  get { return moneda; }
		  set { moneda = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "MontoContabilidad", IsRequired = false, Order = 2)]
		public double MontoContabilidad
		{
		  get { return montoContabilidad; }
		  set { montoContabilidad = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "MontoSistema", IsRequired = false, Order = 3)]
		public double MontoSistema
		{
		  get { return montoSistema; }
		  set { montoSistema = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "CuentaAlterna", IsRequired = false, Order = 4)]
		public string CuentaAlterna
		{
		  get { return cuentaAlterna; }
		  set { cuentaAlterna = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Tolerancia", IsRequired = false, Order = 5)]
		public double Tolerancia
		{
		  get { return tolerancia; }
		  set { tolerancia = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estado", IsRequired = false, Order = 6)]
		public string Estado
		{
		  get { return estado; }
		  set { estado = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Diferencia", IsRequired = false, Order = 7)]
		public double Diferencia
		{
		  get { return diferencia; }
		  set { diferencia = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Comentarios", IsRequired = false, Order = 8)]
		public string Comentarios
		{
		  get { return comentarios; }
		  set { comentarios = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "ValidacionId", IsRequired = false, Order = 9)]
		public int ValidacionId
		{
		  get { return validacionId; }
		  set { validacionId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "RegistroId", IsRequired = false, Order = 10)]
		public int RegistroId
		{
		  get { return registroId; }
		  set { registroId = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "HabilitaAplicaRevision", IsRequired = false, Order = 11)]
		public int HabilitaAplicaRevision
		{
		  get { return habilitaAplicaRevision; }
		  set { habilitaAplicaRevision = value; }
		}				
	}
}

