//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WcfSerialization = global::System.Runtime.Serialization;

namespace Abaseguros.Finanzas.SIAC.DataContracts
{
	/// <summary>
	/// Data Contract Class - ValoresInicialesReporteSeguimiento
	/// </summary>	
	[WcfSerialization::DataContract(Namespace = "http://abaseguros.com", Name = "ValoresInicialesReporteSeguimiento")]
	public partial class ValoresInicialesReporteSeguimiento 
	{
		private System.Nullable<int> businessUnit;
		private System.Nullable<int> sistema;
		private System.Nullable<int> estatus;
		private System.Nullable<System.DateTime> fechaInicial;
		private System.Nullable<System.DateTime> fechaFinal;
		
		[WcfSerialization::DataMember(Name = "BusinessUnit", IsRequired = false, Order = 0)]
		public System.Nullable<int> BusinessUnit
		{
		  get { return businessUnit; }
		  set { businessUnit = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Sistema", IsRequired = false, Order = 1)]
		public System.Nullable<int> Sistema
		{
		  get { return sistema; }
		  set { sistema = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "Estatus", IsRequired = false, Order = 2)]
		public System.Nullable<int> Estatus
		{
		  get { return estatus; }
		  set { estatus = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaInicial", IsRequired = false, Order = 3)]
		public System.Nullable<System.DateTime> FechaInicial
		{
		  get { return fechaInicial; }
		  set { fechaInicial = value; }
		}				
		
		[WcfSerialization::DataMember(Name = "FechaFinal", IsRequired = false, Order = 4)]
		public System.Nullable<System.DateTime> FechaFinal
		{
		  get { return fechaFinal; }
		  set { fechaFinal = value; }
		}				
	}
}

