//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://abaseguros.com", ClrNamespace="abaseguros.com")]

namespace abaseguros.com
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PeriodosCollectionDC", Namespace="http://abaseguros.com", ItemName="PeriodoDC")]
    public class PeriodosCollectionDC : System.Collections.Generic.List<abaseguros.com.PeriodoDC>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodoDC", Namespace="http://abaseguros.com")]
    public partial class PeriodoDC : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdPeriodoField;
        
        private byte IdEstadoField;
        
        private decimal TipoCambioField;
        
        private decimal TipoCambioHOField;
        
        private System.DateTime FechaModificacionField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdPeriodo
        {
            get
            {
                return this.IdPeriodoField;
            }
            set
            {
                this.IdPeriodoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte IdEstado
        {
            get
            {
                return this.IdEstadoField;
            }
            set
            {
                this.IdEstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal TipoCambio
        {
            get
            {
                return this.TipoCambioField;
            }
            set
            {
                this.TipoCambioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal TipoCambioHO
        {
            get
            {
                return this.TipoCambioHOField;
            }
            set
            {
                this.TipoCambioHOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime FechaModificacion
        {
            get
            {
                return this.FechaModificacionField;
            }
            set
            {
                this.FechaModificacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PeriodoIdMessageIn", Namespace="http://abaseguros.com")]
    public partial class PeriodoIdMessageIn : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte EstadoIdField;
        
        private int PeriodoIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte EstadoId
        {
            get
            {
                return this.EstadoIdField;
            }
            set
            {
                this.EstadoIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PeriodoId
        {
            get
            {
                return this.PeriodoIdField;
            }
            set
            {
                this.PeriodoIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://abaseguros.com", ConfigurationName="PeriodoServiceContract")]
public interface PeriodoServiceContract
{
    
    // CODEGEN: Generating message contract since the operation ObtienePeriodos is neither RPC nor document wrapped.
    [System.ServiceModel.OperationContractAttribute(Action="ObtienePeriodos", ReplyAction="http://abaseguros.com/PeriodoServiceContract/ObtienePeriodosResponse")]
    PeriodosMessageOut ObtienePeriodos(ObtienePeriodosRequest request);
    
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class ObtienePeriodosRequest
{
    
    public ObtienePeriodosRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class PeriodosMessageOut
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://abaseguros.com", Order=0)]
    public abaseguros.com.PeriodosCollectionDC ListaPeriodos;
    
    public PeriodosMessageOut()
    {
    }
    
    public PeriodosMessageOut(abaseguros.com.PeriodosCollectionDC ListaPeriodos)
    {
        this.ListaPeriodos = ListaPeriodos;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class PeriodoIdMessageIn
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="PeriodoIdMessageIn", Namespace="http://abaseguros.com", Order=0)]
    public abaseguros.com.PeriodoIdMessageIn PeriodoIdMessageIn1;
    
    public PeriodoIdMessageIn()
    {
    }
    
    public PeriodoIdMessageIn(abaseguros.com.PeriodoIdMessageIn PeriodoIdMessageIn1)
    {
        this.PeriodoIdMessageIn1 = PeriodoIdMessageIn1;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface PeriodoServiceContractChannel : PeriodoServiceContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class PeriodoServiceContractClient : System.ServiceModel.ClientBase<PeriodoServiceContract>, PeriodoServiceContract
{
    
    public PeriodoServiceContractClient()
    {
    }
    
    public PeriodoServiceContractClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PeriodoServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PeriodoServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PeriodoServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    PeriodosMessageOut PeriodoServiceContract.ObtienePeriodos(ObtienePeriodosRequest request)
    {
        return base.Channel.ObtienePeriodos(request);
    }
    
    public abaseguros.com.PeriodosCollectionDC ObtienePeriodos()
    {
        ObtienePeriodosRequest inValue = new ObtienePeriodosRequest();
        PeriodosMessageOut retVal = ((PeriodoServiceContract)(this)).ObtienePeriodos(inValue);
        return retVal.ListaPeriodos;
    }
    
}
