
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ActualizaResultadosPrevalidacionRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "ActualizaResultadosPrevalidacionRequest", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ActualizaResultadosPrevalidacionRequest
	{
		private Abaseguros.Finanzas.SIAC.DataContracts.ActualizaPrevalidacionParametrosCollection parametros;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "Parametros")]
		public Abaseguros.Finanzas.SIAC.DataContracts.ActualizaPrevalidacionParametrosCollection Parametros
		{
			get { return parametros; }
			set { parametros = value; }
		}
	}
}

