
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - HistorialROResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class HistorialROResponse
	{
		private Abaseguros.Finanzas.SIAC.DataContracts.HistorialROCollectionDC historialRO;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "HistorialRO")]
		public Abaseguros.Finanzas.SIAC.DataContracts.HistorialROCollectionDC HistorialRO
		{
			get { return historialRO; }
			set { historialRO = value; }
		}
	}
}

