
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - HistorialRORequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "HistorialRORequest", WrapperNamespace = "http://abaseguros.com")] 
	public partial class HistorialRORequest
	{
		private System.DateTime fechaValidacion;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "FechaValidacion")]
		public System.DateTime FechaValidacion
		{
			get { return fechaValidacion; }
			set { fechaValidacion = value; }
		}
	}
}

