
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - InsertarReportePosValidacionRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "InsertarReportePosValidacionRequest", WrapperNamespace = "http://abaseguros.com")] 
	public partial class InsertarReportePosValidacionRequest
	{
		private string archivo;
	 	private int businessUnit;
	 	private System.DateTime fechaValidacion;
	 	private int tipoArchivo;
	 	private int tipoValidacion;
	 	private string usuario;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "Archivo")]
		public string Archivo
		{
			get { return archivo; }
			set { archivo = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "BusinessUnit")]
		public int BusinessUnit
		{
			get { return businessUnit; }
			set { businessUnit = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "FechaValidacion")]
		public System.DateTime FechaValidacion
		{
			get { return fechaValidacion; }
			set { fechaValidacion = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "TipoArchivo")]
		public int TipoArchivo
		{
			get { return tipoArchivo; }
			set { tipoArchivo = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "TipoValidacion")]
		public int TipoValidacion
		{
			get { return tipoValidacion; }
			set { tipoValidacion = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "Usuario")]
		public string Usuario
		{
			get { return usuario; }
			set { usuario = value; }
		}
	}
}

