
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ObtenerReporteDeSeguimientoValoresInicialesRequest
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class ObtenerReporteDeSeguimientoValoresInicialesRequest
	{
		private string loginUsuario;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "LoginUsuario")]
		public string LoginUsuario
		{
			get { return loginUsuario; }
			set { loginUsuario = value; }
		}
	}
}

