
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ObtieneReporteMonitoreoPSRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "ObtieneReporteMonitoreoPSRequest", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ObtieneReporteMonitoreoPSRequest
	{
		private int procesoId;
	 	private int dia;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "ProcesoId")]
		public int ProcesoId
		{
			get { return procesoId; }
			set { procesoId = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "Dia")]
		public int Dia
		{
			get { return dia; }
			set { dia = value; }
		}
	}
}

