
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ObtieneDashboardPreValidacionRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "ObtieneDashboardPreValidacionRequest", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ObtieneDashboardPreValidacionRequest
	{
		private Abaseguros.Finanzas.SIAC.DataContracts.Request_BU_Sistema_Plaza_PeriodoDC request_BU_Sistema_Plaza_Periodo;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "Request_BU_Sistema_Plaza_Periodo")]
		public Abaseguros.Finanzas.SIAC.DataContracts.Request_BU_Sistema_Plaza_PeriodoDC Request_BU_Sistema_Plaza_Periodo
		{
			get { return request_BU_Sistema_Plaza_Periodo; }
			set { request_BU_Sistema_Plaza_Periodo = value; }
		}
	}
}

