
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ObtieneBitacoraHistorialResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "ObtieneBitacoraHistorialResponse", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ObtieneBitacoraHistorialResponse
	{
		private Abaseguros.Finanzas.SIAC.DataContracts.ObtieneBitacoraCollectionDC obtieneBitacora;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "ObtieneBitacora")]
		public Abaseguros.Finanzas.SIAC.DataContracts.ObtieneBitacoraCollectionDC ObtieneBitacora
		{
			get { return obtieneBitacora; }
			set { obtieneBitacora = value; }
		}
	}
}

