
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ObtieneMensajesReportePosValidacionRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "ObtieneMensajesReportePosValidacionRequest", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ObtieneMensajesReportePosValidacionRequest
	{
		private int businessUnit;
	 	private System.DateTime fechaValidacion;
	 	private int tipoArchivo;
	 	private int tipoValidacion;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "BusinessUnit")]
		public int BusinessUnit
		{
			get { return businessUnit; }
			set { businessUnit = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "FechaValidacion")]
		public System.DateTime FechaValidacion
		{
			get { return fechaValidacion; }
			set { fechaValidacion = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "TipoArchivo")]
		public int TipoArchivo
		{
			get { return tipoArchivo; }
			set { tipoArchivo = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "TipoValidacion")]
		public int TipoValidacion
		{
			get { return tipoValidacion; }
			set { tipoValidacion = value; }
		}
	}
}

