
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ObtieneParametroVarcharRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "ObtieneParametroVarcharRequest", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ObtieneParametroVarcharRequest
	{
		private string descripcion;
	 	private int idParametroField;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "Descripcion")]
		public string Descripcion
		{
			get { return descripcion; }
			set { descripcion = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "idParametro")]
		public int idParametro
		{
			get { return idParametroField; }
			set { idParametroField = value; }
		}
	}
}

