
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ObtieneTipoCambioResponse
	/// </summary>
	[WCF::MessageContract(IsWrapped = false)] 
	public partial class ObtieneTipoCambioResponse
	{
		private Abaseguros.Finanzas.SIAC.DataContracts.TipoCambioCollectionDC tiposCambio;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "TiposCambio")]
		public Abaseguros.Finanzas.SIAC.DataContracts.TipoCambioCollectionDC TiposCambio
		{
			get { return tiposCambio; }
			set { tiposCambio = value; }
		}
	}
}

