
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ObtieneDashboardMonitoreoPCWResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "ObtieneDashboardMonitoreoPCWResponse", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ObtieneDashboardMonitoreoPCWResponse
	{
		private Abaseguros.Finanzas.SIAC.DataContracts.InformacionDashboardMonitoreoCollectionDC informacionDashboardMonitoreo;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "InformacionDashboardMonitoreo")]
		public Abaseguros.Finanzas.SIAC.DataContracts.InformacionDashboardMonitoreoCollectionDC InformacionDashboardMonitoreo
		{
			get { return informacionDashboardMonitoreo; }
			set { informacionDashboardMonitoreo = value; }
		}
	}
}

