
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ObtieneReporteMonitoreoPCWResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "ObtieneReporteMonitoreoPCWResponse", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ObtieneReporteMonitoreoPCWResponse
	{
		private Abaseguros.Finanzas.SIAC.DataContracts.ReporteMonitoreoPCWCollectionDC reporteMonitoreoPCW;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "ReporteMonitoreoPCW")]
		public Abaseguros.Finanzas.SIAC.DataContracts.ReporteMonitoreoPCWCollectionDC ReporteMonitoreoPCW
		{
			get { return reporteMonitoreoPCW; }
			set { reporteMonitoreoPCW = value; }
		}
	}
}

