
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ObtieneDashboardMonitoreoPSRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "ObtieneDashboardMonitoreoPSRequest", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ObtieneDashboardMonitoreoPSRequest
	{
		private int businessUnit;
	 	private int sistemaId;
	 	private int periodoId;
	 	private int estatus;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "BusinessUnit")]
		public int BusinessUnit
		{
			get { return businessUnit; }
			set { businessUnit = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "SistemaId")]
		public int SistemaId
		{
			get { return sistemaId; }
			set { sistemaId = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "PeriodoId")]
		public int PeriodoId
		{
			get { return periodoId; }
			set { periodoId = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "Estatus")]
		public int Estatus
		{
			get { return estatus; }
			set { estatus = value; }
		}
	}
}

