
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ObtieneResultadosPreValidacionResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "ObtieneResultadosPreValidacionResponse", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ObtieneResultadosPreValidacionResponse
	{
		private Abaseguros.Finanzas.SIAC.DataContracts.ResultadosPreValidacionCollectionDC resultadosPreValidacionCollectionDC;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "ResultadosPreValidacionCollectionDC")]
		public Abaseguros.Finanzas.SIAC.DataContracts.ResultadosPreValidacionCollectionDC ResultadosPreValidacionCollectionDC
		{
			get { return resultadosPreValidacionCollectionDC; }
			set { resultadosPreValidacionCollectionDC = value; }
		}
	}
}

