
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ObtieneParametroVarcharResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "ObtieneParametroVarcharResponse", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ObtieneParametroVarcharResponse
	{
		private string valorVarchar;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "ValorVarchar")]
		public string ValorVarchar
		{
			get { return valorVarchar; }
			set { valorVarchar = value; }
		}
	}
}

