
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ObtienePeriodosRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "ObtienePeriodosRequest", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ObtienePeriodosRequest
	{
		private int anio;
	 	private int businessUnit;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "Anio")]
		public int Anio
		{
			get { return anio; }
			set { anio = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "BusinessUnit")]
		public int BusinessUnit
		{
			get { return businessUnit; }
			set { businessUnit = value; }
		}
	}
}

