
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ObtieneBitacoraReporteRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "ObtieneBitacoraReporteRequest", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ObtieneBitacoraReporteRequest
	{
		private int businessUnit;
	 	private int tipoArchivo;
	 	private int tipoValidacion;
	 	private System.DateTime fecha;
	 	private string usuario;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "BusinessUnit")]
		public int BusinessUnit
		{
			get { return businessUnit; }
			set { businessUnit = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "TipoArchivo")]
		public int TipoArchivo
		{
			get { return tipoArchivo; }
			set { tipoArchivo = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "TipoValidacion")]
		public int TipoValidacion
		{
			get { return tipoValidacion; }
			set { tipoValidacion = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "Fecha")]
		public System.DateTime Fecha
		{
			get { return fecha; }
			set { fecha = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "Usuario")]
		public string Usuario
		{
			get { return usuario; }
			set { usuario = value; }
		}
	}
}

