
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ParametroReporteResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "ParametroReporteResponse", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ParametroReporteResponse
	{
		private int idSesionField;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "idSesion")]
		public int idSesion
		{
			get { return idSesionField; }
			set { idSesionField = value; }
		}
	}
}

