
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - PlazaResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "PlazaResponse", WrapperNamespace = "http://abaseguros.com")] 
	public partial class PlazaResponse
	{
		private Abaseguros.Finanzas.SIAC.DataContracts.PlazaDC plaza;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "Plaza")]
		public Abaseguros.Finanzas.SIAC.DataContracts.PlazaDC Plaza
		{
			get { return plaza; }
			set { plaza = value; }
		}
	}
}

