
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ProcesaPreValidacionRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "ProcesaPreValidacionRequest", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ProcesaPreValidacionRequest
	{
		private Abaseguros.Finanzas.SIAC.DataContracts.Request_BU_Sistema_Plaza_FechaValDC request_BU_Sistema_Plaza_FechaVal;
	 	private string login;
	 	private int cargaRO;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "Request_BU_Sistema_Plaza_FechaVal")]
		public Abaseguros.Finanzas.SIAC.DataContracts.Request_BU_Sistema_Plaza_FechaValDC Request_BU_Sistema_Plaza_FechaVal
		{
			get { return request_BU_Sistema_Plaza_FechaVal; }
			set { request_BU_Sistema_Plaza_FechaVal = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "Login")]
		public string Login
		{
			get { return login; }
			set { login = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "CargaRO")]
		public int CargaRO
		{
			get { return cargaRO; }
			set { cargaRO = value; }
		}
	}
}

