
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ResultadoPosValidacionRequest
	/// </summary>
	[WCF::MessageContract(WrapperName = "ResultadoPosValidacionRequest", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ResultadoPosValidacionRequest
	{
		private Abaseguros.Finanzas.SIAC.DataContracts.Request_BU_Sistema_Plaza_FechaValDC bU_Sistema_Plaza_FechaValDC;
	 	private int tipoValidacionId;
	 	private int archivoPosvalidacionId;
	 		
		/// <remarks>TipoValidacion</remarks>
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "BU_Sistema_Plaza_FechaValDC")]
		public Abaseguros.Finanzas.SIAC.DataContracts.Request_BU_Sistema_Plaza_FechaValDC BU_Sistema_Plaza_FechaValDC
		{
			get { return bU_Sistema_Plaza_FechaValDC; }
			set { bU_Sistema_Plaza_FechaValDC = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "TipoValidacionId")]
		public int TipoValidacionId
		{
			get { return tipoValidacionId; }
			set { tipoValidacionId = value; }
		}
			
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "ArchivoPosvalidacionId")]
		public int ArchivoPosvalidacionId
		{
			get { return archivoPosvalidacionId; }
			set { archivoPosvalidacionId = value; }
		}
	}
}

