
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.MessageContracts
{
	/// <summary>
	/// Service Contract Class - ResultadoPosValidacionResponse
	/// </summary>
	[WCF::MessageContract(WrapperName = "ResultadoPosValidacionResponse", WrapperNamespace = "http://abaseguros.com")] 
	public partial class ResultadoPosValidacionResponse
	{
		private Abaseguros.Finanzas.SIAC.DataContracts.ResultadosPosValidacionCollectionDC resultadosPosValidacionCollectionDC;
	 		
		[WCF::MessageBodyMember(Namespace = "http://abaseguros.com", Name = "ResultadosPosValidacionCollectionDC")]
		public Abaseguros.Finanzas.SIAC.DataContracts.ResultadosPosValidacionCollectionDC ResultadosPosValidacionCollectionDC
		{
			get { return resultadosPosValidacionCollectionDC; }
			set { resultadosPosValidacionCollectionDC = value; }
		}
	}
}

