//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.ServiceImplementation
{
    /// <summary>
    /// Service Class - MonitoreoPCWService
    /// </summary>
    [WCF::ServiceBehavior(Name = "MonitoreoPCWService",
        Namespace = "http://abaseguros.com",
        InstanceContextMode = WCF::InstanceContextMode.PerSession,
        ConcurrencyMode = WCF::ConcurrencyMode.Single)]
    public abstract class MonitoreoPCWServiceBase : Abaseguros.Finanzas.SIAC.ServiceContracts.IMonitoreoPCWServiceContract
    {
        #region MonitoreoPCWServiceContract Members

        public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardMonitoreoPCWResponse ObtieneDashboardMonitoreoPCW(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardMonitoreoPCWRequest request)
        {
            return null;
        }

        public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteMonitoreoPCWResponse ObtieneReporteMonitoreoPCW(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteMonitoreoPCWRequest request)
        {
            return null;
        }

        public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteCalendarioPCWResponse ObtieneReporteCalendarioPCW(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteCalendarioPCWRequest request)
        {
            return null;
        }

        #endregion		

    }

    public partial class MonitoreoPCWService : MonitoreoPCWServiceBase
    {
        BusinessLogic.MonitoreoPCWBL _objMonitoreoPCWBL = new BusinessLogic.MonitoreoPCWBL();

        public override Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardMonitoreoPCWResponse ObtieneDashboardMonitoreoPCW(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardMonitoreoPCWRequest request)
        {
            MessageContracts.ObtieneDashboardMonitoreoPCWResponse objObtieneDashboardMonitoreoPCWResponse = new MessageContracts.ObtieneDashboardMonitoreoPCWResponse();
            DataContracts.InformacionDashboardMonitoreoCollectionDC lstInformacionDashboardMonitoreoCollectionDC = new DataContracts.InformacionDashboardMonitoreoCollectionDC();
            DataContracts.InformacionDashboardMonitoreoDC objInformacionDashboardMonitoreoDC = null;
            List<BusinessEntities.InformacionDashboardMonitoreo> lstInformacionDashboardMonitoreo;

            lstInformacionDashboardMonitoreo = _objMonitoreoPCWBL.ObtieneDashboardMonitoreoPCW(request.BusinessUnit,
                                                                                              request.ArchivoId,
                                                                                              request.PeriodoId,
                                                                                              request.Estatus);

            foreach (BusinessEntities.InformacionDashboardMonitoreo objInformacionDashboardMonitoreo in lstInformacionDashboardMonitoreo)
            {
                objInformacionDashboardMonitoreoDC = new DataContracts.InformacionDashboardMonitoreoDC();
                objInformacionDashboardMonitoreoDC.DiasMes = new DataContracts.DiasMesDC();

                objInformacionDashboardMonitoreoDC.ProcesoId = objInformacionDashboardMonitoreo.ProcesoId;
                objInformacionDashboardMonitoreoDC.Aplicacion = objInformacionDashboardMonitoreo.Aplicacion;
                objInformacionDashboardMonitoreoDC.BusinessUnit = objInformacionDashboardMonitoreo.BusinessUnit;
                objInformacionDashboardMonitoreoDC.ArchivoPCWId = objInformacionDashboardMonitoreo.ArchivoPCWId;
                objInformacionDashboardMonitoreoDC.DiasMes.D1 = objInformacionDashboardMonitoreo.DiasMes.D1;
                objInformacionDashboardMonitoreoDC.DiasMes.D2 = objInformacionDashboardMonitoreo.DiasMes.D2;
                objInformacionDashboardMonitoreoDC.DiasMes.D3 = objInformacionDashboardMonitoreo.DiasMes.D3;
                objInformacionDashboardMonitoreoDC.DiasMes.D4 = objInformacionDashboardMonitoreo.DiasMes.D4;
                objInformacionDashboardMonitoreoDC.DiasMes.D5 = objInformacionDashboardMonitoreo.DiasMes.D5;
                objInformacionDashboardMonitoreoDC.DiasMes.D6 = objInformacionDashboardMonitoreo.DiasMes.D6;
                objInformacionDashboardMonitoreoDC.DiasMes.D7 = objInformacionDashboardMonitoreo.DiasMes.D7;
                objInformacionDashboardMonitoreoDC.DiasMes.D8 = objInformacionDashboardMonitoreo.DiasMes.D8;
                objInformacionDashboardMonitoreoDC.DiasMes.D9 = objInformacionDashboardMonitoreo.DiasMes.D9;
                objInformacionDashboardMonitoreoDC.DiasMes.D10 = objInformacionDashboardMonitoreo.DiasMes.D10;
                objInformacionDashboardMonitoreoDC.DiasMes.D11 = objInformacionDashboardMonitoreo.DiasMes.D11;
                objInformacionDashboardMonitoreoDC.DiasMes.D12 = objInformacionDashboardMonitoreo.DiasMes.D12;
                objInformacionDashboardMonitoreoDC.DiasMes.D13 = objInformacionDashboardMonitoreo.DiasMes.D13;
                objInformacionDashboardMonitoreoDC.DiasMes.D14 = objInformacionDashboardMonitoreo.DiasMes.D14;
                objInformacionDashboardMonitoreoDC.DiasMes.D15 = objInformacionDashboardMonitoreo.DiasMes.D15;
                objInformacionDashboardMonitoreoDC.DiasMes.D16 = objInformacionDashboardMonitoreo.DiasMes.D16;
                objInformacionDashboardMonitoreoDC.DiasMes.D17 = objInformacionDashboardMonitoreo.DiasMes.D17;
                objInformacionDashboardMonitoreoDC.DiasMes.D18 = objInformacionDashboardMonitoreo.DiasMes.D18;
                objInformacionDashboardMonitoreoDC.DiasMes.D19 = objInformacionDashboardMonitoreo.DiasMes.D19;
                objInformacionDashboardMonitoreoDC.DiasMes.D20 = objInformacionDashboardMonitoreo.DiasMes.D20;
                objInformacionDashboardMonitoreoDC.DiasMes.D21 = objInformacionDashboardMonitoreo.DiasMes.D21;
                objInformacionDashboardMonitoreoDC.DiasMes.D22 = objInformacionDashboardMonitoreo.DiasMes.D22;
                objInformacionDashboardMonitoreoDC.DiasMes.D23 = objInformacionDashboardMonitoreo.DiasMes.D23;
                objInformacionDashboardMonitoreoDC.DiasMes.D24 = objInformacionDashboardMonitoreo.DiasMes.D24;
                objInformacionDashboardMonitoreoDC.DiasMes.D25 = objInformacionDashboardMonitoreo.DiasMes.D25;
                objInformacionDashboardMonitoreoDC.DiasMes.D26 = objInformacionDashboardMonitoreo.DiasMes.D26;
                objInformacionDashboardMonitoreoDC.DiasMes.D27 = objInformacionDashboardMonitoreo.DiasMes.D27;
                objInformacionDashboardMonitoreoDC.DiasMes.D28 = objInformacionDashboardMonitoreo.DiasMes.D28;
                objInformacionDashboardMonitoreoDC.DiasMes.D29 = objInformacionDashboardMonitoreo.DiasMes.D29;
                objInformacionDashboardMonitoreoDC.DiasMes.D30 = objInformacionDashboardMonitoreo.DiasMes.D30;
                objInformacionDashboardMonitoreoDC.DiasMes.D31 = objInformacionDashboardMonitoreo.DiasMes.D31;

                lstInformacionDashboardMonitoreoCollectionDC.Add(objInformacionDashboardMonitoreoDC);
            }

            objObtieneDashboardMonitoreoPCWResponse.InformacionDashboardMonitoreo = lstInformacionDashboardMonitoreoCollectionDC;
            return objObtieneDashboardMonitoreoPCWResponse;
        }

        public override Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteMonitoreoPCWResponse ObtieneReporteMonitoreoPCW(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteMonitoreoPCWRequest request)
        {
            MessageContracts.ObtieneReporteMonitoreoPCWResponse objObtieneReporteMonitoreoPCWResponse = new MessageContracts.ObtieneReporteMonitoreoPCWResponse();
            DataContracts.ReporteMonitoreoPCWCollectionDC lstReporteMonitoreoPCWCollectionDC = new DataContracts.ReporteMonitoreoPCWCollectionDC();
            DataContracts.ReporteMonitoreoPCWDC objReporteMonitoreoPCWDC = null;
            List<BusinessEntities.ReporteMonitoreoPCW> lstReporteMonitoreoPCW;

            lstReporteMonitoreoPCW = _objMonitoreoPCWBL.ObtieneReporteMonitoreoPCW(request.ArchivoId, request.Dia);

            foreach (BusinessEntities.ReporteMonitoreoPCW objReporteMonitoreoPCW in lstReporteMonitoreoPCW)
            {
                objReporteMonitoreoPCWDC = new DataContracts.ReporteMonitoreoPCWDC();

                objReporteMonitoreoPCWDC.Compania = objReporteMonitoreoPCW.Compania;
                objReporteMonitoreoPCWDC.Archivo = objReporteMonitoreoPCW.Archivo;
                objReporteMonitoreoPCWDC.ProcesoId = objReporteMonitoreoPCW.ProcesoId;
                objReporteMonitoreoPCWDC.VoucherABA = objReporteMonitoreoPCW.VoucherABA;
                objReporteMonitoreoPCWDC.FechaContable = objReporteMonitoreoPCW.FechaContable;
                objReporteMonitoreoPCWDC.Sistema = objReporteMonitoreoPCW.Sistema;
                objReporteMonitoreoPCWDC.Plaza = objReporteMonitoreoPCW.Plaza;
                objReporteMonitoreoPCWDC.Estado = objReporteMonitoreoPCW.Estado;

                lstReporteMonitoreoPCWCollectionDC.Add(objReporteMonitoreoPCWDC);
            }

            objObtieneReporteMonitoreoPCWResponse.ReporteMonitoreoPCW = lstReporteMonitoreoPCWCollectionDC;
            return objObtieneReporteMonitoreoPCWResponse;
        }

        public override Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteCalendarioPCWResponse ObtieneReporteCalendarioPCW(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteCalendarioPCWRequest request)
        {
            MessageContracts.ObtieneReporteCalendarioPCWResponse objObtieneReporteCalendarioPCWResponse = new MessageContracts.ObtieneReporteCalendarioPCWResponse();
            DataContracts.ReporteCalendarioPCWCollectionDC lstReporteCalendarioPCWCollectionDC = new DataContracts.ReporteCalendarioPCWCollectionDC();
            DataContracts.ReporteCalendarioPCWDC objReporteCalendarioPCWDC = null;
            List<BusinessEntities.ReporteCalendarioPCW> lstReporteCalendarioPCW;

            lstReporteCalendarioPCW = _objMonitoreoPCWBL.ObtieneReporteCalendarioPCW(request.ArchivoId, request.Dia);

            foreach (BusinessEntities.ReporteCalendarioPCW objReporteCalendarioPCW in lstReporteCalendarioPCW)
            {
                objReporteCalendarioPCWDC = new DataContracts.ReporteCalendarioPCWDC();

                objReporteCalendarioPCWDC.Compania = objReporteCalendarioPCW.Compania;
                objReporteCalendarioPCWDC.Archivo = objReporteCalendarioPCW.Archivo;
                objReporteCalendarioPCWDC.FechaInicio = objReporteCalendarioPCW.FechaInicio;
                objReporteCalendarioPCWDC.FechaFin = objReporteCalendarioPCW.FechaFin;
                objReporteCalendarioPCWDC.Semana = objReporteCalendarioPCW.Semana;
                objReporteCalendarioPCWDC.PeriodoId = objReporteCalendarioPCW.PeriodoId;

                lstReporteCalendarioPCWCollectionDC.Add(objReporteCalendarioPCWDC);
            }

            objObtieneReporteCalendarioPCWResponse.ReporteCalendarioPCW = lstReporteCalendarioPCWCollectionDC;
            return objObtieneReporteCalendarioPCWResponse;
        }
    }
}

