//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.ServiceImplementation
{
    /// <summary>
    /// Service Class - MonitoreoPSService
    /// </summary>
    [WCF::ServiceBehavior(Name = "MonitoreoPSService",
        Namespace = "http://abaseguros.com",
        InstanceContextMode = WCF::InstanceContextMode.PerSession,
        ConcurrencyMode = WCF::ConcurrencyMode.Single)]
    public abstract class MonitoreoPSServiceBase : Abaseguros.Finanzas.SIAC.ServiceContracts.IMonitoreoPSServiceContract
    {
        #region MonitoreoPSServiceContract Members

        public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardMonitoreoPSResponse ObtieneDashboardMonitoreoPS(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardMonitoreoPSRequest request)
        {
            return null;
        }

        public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteMonitoreoPSResponse ObtieneReporteMonitoreoPS(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteMonitoreoPSRequest request)
        {
            return null;
        }

        public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ObtenerReporteDeSeguimientoValoresInicialesResponse ObtenerReporteDeSeguimientoValoresIniciales(Abaseguros.Finanzas.SIAC.MessageContracts.ObtenerReporteDeSeguimientoValoresInicialesRequest request)
        {
            return null;
        }

        #endregion		
    }

    public partial class MonitoreoPSService : MonitoreoPSServiceBase
    {
        BusinessLogic.MonitoreoPSBL _objMonitoreoPSBL = new BusinessLogic.MonitoreoPSBL();

        public override Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardMonitoreoPSResponse ObtieneDashboardMonitoreoPS(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardMonitoreoPSRequest request)
        {
            MessageContracts.ObtieneDashboardMonitoreoPSResponse objObtieneDashboardMonitoreoPSResponse = new MessageContracts.ObtieneDashboardMonitoreoPSResponse();
            DataContracts.InformacionDashboardMonitoreoCollectionDC lstInformacionDashboardMonitoreoCollectionDC = new DataContracts.InformacionDashboardMonitoreoCollectionDC();
            DataContracts.InformacionDashboardMonitoreoDC objInformacionDashboardMonitoreoDC = null;
            
            List<BusinessEntities.InformacionDashboardMonitoreo> lstInformacionDashboardMonitoreo;

            lstInformacionDashboardMonitoreo = _objMonitoreoPSBL.ObtieneDashboardMonitoreoPS(request.BusinessUnit,
                                                                                            request.SistemaId,
                                                                                            request.PeriodoId,
                                                                                            request.Estatus);

            foreach (BusinessEntities.InformacionDashboardMonitoreo objInformacionDashboardMonitoreo in lstInformacionDashboardMonitoreo)
            {
                objInformacionDashboardMonitoreoDC = new DataContracts.InformacionDashboardMonitoreoDC();
                objInformacionDashboardMonitoreoDC.DiasMes = new DataContracts.DiasMesDC();

                objInformacionDashboardMonitoreoDC.ProcesoId = objInformacionDashboardMonitoreo.ProcesoId;
                objInformacionDashboardMonitoreoDC.Aplicacion = objInformacionDashboardMonitoreo.Aplicacion;
                objInformacionDashboardMonitoreoDC.BusinessUnit = objInformacionDashboardMonitoreo.BusinessUnit;
                objInformacionDashboardMonitoreoDC.DiasMes.D1 = objInformacionDashboardMonitoreo.DiasMes.D1;
                objInformacionDashboardMonitoreoDC.DiasMes.D2 = objInformacionDashboardMonitoreo.DiasMes.D2;
                objInformacionDashboardMonitoreoDC.DiasMes.D3 = objInformacionDashboardMonitoreo.DiasMes.D3;
                objInformacionDashboardMonitoreoDC.DiasMes.D4 = objInformacionDashboardMonitoreo.DiasMes.D4;
                objInformacionDashboardMonitoreoDC.DiasMes.D5 = objInformacionDashboardMonitoreo.DiasMes.D5;
                objInformacionDashboardMonitoreoDC.DiasMes.D6 = objInformacionDashboardMonitoreo.DiasMes.D6;
                objInformacionDashboardMonitoreoDC.DiasMes.D7 = objInformacionDashboardMonitoreo.DiasMes.D7;
                objInformacionDashboardMonitoreoDC.DiasMes.D8 = objInformacionDashboardMonitoreo.DiasMes.D8;
                objInformacionDashboardMonitoreoDC.DiasMes.D9 = objInformacionDashboardMonitoreo.DiasMes.D9;
                objInformacionDashboardMonitoreoDC.DiasMes.D10 = objInformacionDashboardMonitoreo.DiasMes.D10;
                objInformacionDashboardMonitoreoDC.DiasMes.D11 = objInformacionDashboardMonitoreo.DiasMes.D11;
                objInformacionDashboardMonitoreoDC.DiasMes.D12 = objInformacionDashboardMonitoreo.DiasMes.D12;
                objInformacionDashboardMonitoreoDC.DiasMes.D13 = objInformacionDashboardMonitoreo.DiasMes.D13;
                objInformacionDashboardMonitoreoDC.DiasMes.D14 = objInformacionDashboardMonitoreo.DiasMes.D14;
                objInformacionDashboardMonitoreoDC.DiasMes.D15 = objInformacionDashboardMonitoreo.DiasMes.D15;
                objInformacionDashboardMonitoreoDC.DiasMes.D16 = objInformacionDashboardMonitoreo.DiasMes.D16;
                objInformacionDashboardMonitoreoDC.DiasMes.D17 = objInformacionDashboardMonitoreo.DiasMes.D17;
                objInformacionDashboardMonitoreoDC.DiasMes.D18 = objInformacionDashboardMonitoreo.DiasMes.D18;
                objInformacionDashboardMonitoreoDC.DiasMes.D19 = objInformacionDashboardMonitoreo.DiasMes.D19;
                objInformacionDashboardMonitoreoDC.DiasMes.D20 = objInformacionDashboardMonitoreo.DiasMes.D20;
                objInformacionDashboardMonitoreoDC.DiasMes.D21 = objInformacionDashboardMonitoreo.DiasMes.D21;
                objInformacionDashboardMonitoreoDC.DiasMes.D22 = objInformacionDashboardMonitoreo.DiasMes.D22;
                objInformacionDashboardMonitoreoDC.DiasMes.D23 = objInformacionDashboardMonitoreo.DiasMes.D23;
                objInformacionDashboardMonitoreoDC.DiasMes.D24 = objInformacionDashboardMonitoreo.DiasMes.D24;
                objInformacionDashboardMonitoreoDC.DiasMes.D25 = objInformacionDashboardMonitoreo.DiasMes.D25;
                objInformacionDashboardMonitoreoDC.DiasMes.D26 = objInformacionDashboardMonitoreo.DiasMes.D26;
                objInformacionDashboardMonitoreoDC.DiasMes.D27 = objInformacionDashboardMonitoreo.DiasMes.D27;
                objInformacionDashboardMonitoreoDC.DiasMes.D28 = objInformacionDashboardMonitoreo.DiasMes.D28;
                objInformacionDashboardMonitoreoDC.DiasMes.D29 = objInformacionDashboardMonitoreo.DiasMes.D29;
                objInformacionDashboardMonitoreoDC.DiasMes.D30 = objInformacionDashboardMonitoreo.DiasMes.D30;
                objInformacionDashboardMonitoreoDC.DiasMes.D31 = objInformacionDashboardMonitoreo.DiasMes.D31;
                
                lstInformacionDashboardMonitoreoCollectionDC.Add(objInformacionDashboardMonitoreoDC);
            }

            objObtieneDashboardMonitoreoPSResponse.InformacionDashboardMonitoreo = lstInformacionDashboardMonitoreoCollectionDC;
            return objObtieneDashboardMonitoreoPSResponse;
        }

        public override Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteMonitoreoPSResponse ObtieneReporteMonitoreoPS(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteMonitoreoPSRequest request)
        {
            MessageContracts.ObtieneReporteMonitoreoPSResponse objObtieneReporteMonitoreoPSResponse = new MessageContracts.ObtieneReporteMonitoreoPSResponse();
            DataContracts.ReporteMonitoreoPSCollectionDC lstReporteMonitoreoPSCollectionDC = new DataContracts.ReporteMonitoreoPSCollectionDC();
            DataContracts.ReporteMonitoreoPSDC objReporteMonitoreoPSDC = null;
            List<BusinessEntities.ReporteMonitoreoPS> lstReporteMonitoreoPS;

            lstReporteMonitoreoPS = _objMonitoreoPSBL.ObtieneReporteMonitoreoPS(request.ProcesoId, request.Dia);

            foreach (BusinessEntities.ReporteMonitoreoPS objReporteMonitoreoPS in lstReporteMonitoreoPS)
            {
                objReporteMonitoreoPSDC = new DataContracts.ReporteMonitoreoPSDC();

                objReporteMonitoreoPSDC.BusinessUnit = objReporteMonitoreoPS.BusinessUnit;
                objReporteMonitoreoPSDC.Sistema = objReporteMonitoreoPS.Sistema;
                objReporteMonitoreoPSDC.ProcesoId = objReporteMonitoreoPS.ProcesoId;
                objReporteMonitoreoPSDC.JournalId = objReporteMonitoreoPS.JournalId;
                objReporteMonitoreoPSDC.Ledger = objReporteMonitoreoPS.Ledger;
                objReporteMonitoreoPSDC.FechaContable = objReporteMonitoreoPS.FechaContable;
                objReporteMonitoreoPSDC.Plaza = objReporteMonitoreoPS.Plaza;
                objReporteMonitoreoPSDC.Estado = objReporteMonitoreoPS.Estado;
                objReporteMonitoreoPSDC.Archivo = objReporteMonitoreoPS.Archivo;

                lstReporteMonitoreoPSCollectionDC.Add(objReporteMonitoreoPSDC);
            }

            objObtieneReporteMonitoreoPSResponse.ReporteMonitoreoPS = lstReporteMonitoreoPSCollectionDC;
            return objObtieneReporteMonitoreoPSResponse;
        }

        public override Abaseguros.Finanzas.SIAC.MessageContracts.ObtenerReporteDeSeguimientoValoresInicialesResponse ObtenerReporteDeSeguimientoValoresIniciales(Abaseguros.Finanzas.SIAC.MessageContracts.ObtenerReporteDeSeguimientoValoresInicialesRequest request)
        {
            MessageContracts.ObtenerReporteDeSeguimientoValoresInicialesResponse objResponse = new MessageContracts.ObtenerReporteDeSeguimientoValoresInicialesResponse();
            DataContracts.ValoresInicialesReporteSeguimiento objValoresIniciales = new DataContracts.ValoresInicialesReporteSeguimiento();
            BusinessEntities.ReporteDeSeguimientoValoresIniciales objBE = _objMonitoreoPSBL.ObtenerReporteDeSeguimientoValoresIniciales(request.LoginUsuario);

            objValoresIniciales.BusinessUnit = objBE.BusinessUnit;
            objValoresIniciales.Sistema = objBE.Sistema;
            objValoresIniciales.Estatus = objBE.Estatus;
            objValoresIniciales.FechaInicial = objBE.FechaInicial;
            objValoresIniciales.FechaFinal = objBE.FechaFinal;

            objResponse.ValoresIniciales = objValoresIniciales;
            return objResponse;
        }
    }
}

