//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using WCF = global::System.ServiceModel;
using System.Collections.Generic;

namespace Abaseguros.Finanzas.SIAC.ServiceImplementation
{	
	/// <summary>
	/// Service Class - PeriodoService
	/// </summary>
	[WCF::ServiceBehavior(Name = "PeriodoService", 
		Namespace = "http://abaseguros.com", 
		InstanceContextMode = WCF::InstanceContextMode.PerSession, 
		ConcurrencyMode = WCF::ConcurrencyMode.Single )]
	public abstract class PeriodoServiceBase : Abaseguros.Finanzas.SIAC.ServiceContracts.IPeriodoServiceContract
	{
		#region PeriodoServiceContract Members

		public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ObtienePeriodosResponse ObtienePeriodos(Abaseguros.Finanzas.SIAC.MessageContracts.ObtienePeriodosRequest request)
		{
			return null;
		}

        public virtual void ActualizaEstadoPeriodo(Abaseguros.Finanzas.SIAC.MessageContracts.ActualizaEstadoPeriodoRequest request)
        {
        }

		#endregion		
		
	}
	
	public partial class PeriodoService : PeriodoServiceBase
	{
        BusinessLogic.PeriodoBL _objPeriodoBL = new BusinessLogic.PeriodoBL();
        public override Abaseguros.Finanzas.SIAC.MessageContracts.ObtienePeriodosResponse ObtienePeriodos(Abaseguros.Finanzas.SIAC.MessageContracts.ObtienePeriodosRequest request)
        {
            MessageContracts.ObtienePeriodosResponse msgObtienePeriodoResponse = new MessageContracts.ObtienePeriodosResponse();
            List<BusinessEntities.Periodo> lstPeriodos = new List<BusinessEntities.Periodo>();

            DataContracts.PeriodoDC objPeriodoDC = null;
            DataContracts.PeriodoCollectionDC lstPeriodoCollectionDC = new DataContracts.PeriodoCollectionDC();

            lstPeriodos = _objPeriodoBL.ObtienePeriodos(request.BusinessUnit, request.Anio);
            foreach (BusinessEntities.Periodo objPeriodo in lstPeriodos)
            {
                objPeriodoDC = new DataContracts.PeriodoDC();
                objPeriodoDC.BusinessUnit = objPeriodo.BusinessUnit;
                objPeriodoDC.Periodo = objPeriodo.PeriodoId;
                objPeriodoDC.Estado = objPeriodo.EstadoId;
                objPeriodoDC.FechaModificacion = objPeriodo.FechaModificacion;
                objPeriodoDC.Usuario = objPeriodo.UsuarioModificacion;

                lstPeriodoCollectionDC.Add(objPeriodoDC);
            }

            msgObtienePeriodoResponse.Periodos = lstPeriodoCollectionDC;
            return msgObtienePeriodoResponse;
        }

        public override void ActualizaEstadoPeriodo(Abaseguros.Finanzas.SIAC.MessageContracts.ActualizaEstadoPeriodoRequest request)
        {
            _objPeriodoBL.actualizaPeriodo(request.BusinessUnit, request.Periodo, request.Estado, request.Usuario);

        }
	}
	
}

