//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.ServiceImplementation
{
    /// <summary>
    /// Service Class - PreValidacionService
    /// </summary>
    [WCF::ServiceBehavior(Name = "PreValidacionService",
        Namespace = "http://abaseguros.com",
        InstanceContextMode = WCF::InstanceContextMode.PerSession,
        ConcurrencyMode = WCF::ConcurrencyMode.Single)]
    public abstract class PreValidacionServiceBase : Abaseguros.Finanzas.SIAC.ServiceContracts.IPreValidacionServiceContract
    {
        #region PreValidacionServiceContract Members

        public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardPreValidacionResponse ObtieneDashboardPreValidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardPreValidacionRequest request)
        {
            return null;
        }

        public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ProcesaPreValidacionResponse ProcesaPreValidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ProcesaPreValidacionRequest request)
        {
            return null;
        }

        public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneResultadosPreValidacionResponse ObtieneResultadosPrevalidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneResultadosPreValidacionRequest request)
        {
            return null;
        }

        public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneResultadosPreValidacionResponse ObtieneHistorialPrevalidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneResultadosPreValidacionRequest request)
        {
            return null;
        }

        public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ActualizaResultadosPrevalidacionResponse ActualizaResultadosPrevalidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ActualizaResultadosPrevalidacionRequest request)
        {
            return null;
        }

        public virtual Abaseguros.Finanzas.SIAC.MessageContracts.FechasAcumuladoSiniestros ObtieneAcumuladoSiniestros()
        {
            return null;
        }

        #endregion

    }

    public partial class PreValidacionService : PreValidacionServiceBase
    {
        BusinessLogic.PreValidacionBL _objPreValidacionBL = new BusinessLogic.PreValidacionBL();
        public override Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardPreValidacionResponse ObtieneDashboardPreValidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardPreValidacionRequest request)
        {
            MessageContracts.ObtieneDashboardPreValidacionResponse msgObtieneDashboardPreValidacionResponse = new MessageContracts.ObtieneDashboardPreValidacionResponse();
            List<BusinessEntities.InformacionDashboardValidacion> lstInformacionDashboard = new List<BusinessEntities.InformacionDashboardValidacion>();

            DataContracts.InformacionDashboardValidacionDC objInformacionDashboardValidacionDC = null;
            DataContracts.InformacionDashboardValidacionCollectionDC lstInformacionDashboardValidacionCollectionDC = new DataContracts.InformacionDashboardValidacionCollectionDC();

            lstInformacionDashboard = _objPreValidacionBL.ObtieneDashboardPreValidacion( request.Request_BU_Sistema_Plaza_Periodo.BusinessUnit,
                                                                                        request.Request_BU_Sistema_Plaza_Periodo.idSistema,
                                                                                        request.Request_BU_Sistema_Plaza_Periodo.idPlaza,
                                                                                        request.Request_BU_Sistema_Plaza_Periodo.PeriodoId);
            foreach (BusinessEntities.InformacionDashboardValidacion objInformacionDashboardValidacion in lstInformacionDashboard)
            {
                objInformacionDashboardValidacionDC = new DataContracts.InformacionDashboardValidacionDC();
                objInformacionDashboardValidacionDC.DiasMes = new DataContracts.DiasMesDC();

                objInformacionDashboardValidacionDC.idSistema = objInformacionDashboardValidacion.idSistema;
                objInformacionDashboardValidacionDC.idPlaza = objInformacionDashboardValidacion.idPlaza;
                objInformacionDashboardValidacionDC.SistemaPlaza = objInformacionDashboardValidacion.SistemaPlaza;
                objInformacionDashboardValidacionDC.Cuenta = objInformacionDashboardValidacion.Cuenta;
                objInformacionDashboardValidacionDC.Moneda = objInformacionDashboardValidacion.Moneda;
                objInformacionDashboardValidacionDC.DiasMes.D1 = objInformacionDashboardValidacion.DiasMes.D1;
                objInformacionDashboardValidacionDC.DiasMes.D2 = objInformacionDashboardValidacion.DiasMes.D2;
                objInformacionDashboardValidacionDC.DiasMes.D3 = objInformacionDashboardValidacion.DiasMes.D3;
                objInformacionDashboardValidacionDC.DiasMes.D4 = objInformacionDashboardValidacion.DiasMes.D4;
                objInformacionDashboardValidacionDC.DiasMes.D5 = objInformacionDashboardValidacion.DiasMes.D5;
                objInformacionDashboardValidacionDC.DiasMes.D6 = objInformacionDashboardValidacion.DiasMes.D6;
                objInformacionDashboardValidacionDC.DiasMes.D7 = objInformacionDashboardValidacion.DiasMes.D7;
                objInformacionDashboardValidacionDC.DiasMes.D8 = objInformacionDashboardValidacion.DiasMes.D8;
                objInformacionDashboardValidacionDC.DiasMes.D9 = objInformacionDashboardValidacion.DiasMes.D9;
                objInformacionDashboardValidacionDC.DiasMes.D10 = objInformacionDashboardValidacion.DiasMes.D10;
                objInformacionDashboardValidacionDC.DiasMes.D11 = objInformacionDashboardValidacion.DiasMes.D11;
                objInformacionDashboardValidacionDC.DiasMes.D12 = objInformacionDashboardValidacion.DiasMes.D12;
                objInformacionDashboardValidacionDC.DiasMes.D13 = objInformacionDashboardValidacion.DiasMes.D13;
                objInformacionDashboardValidacionDC.DiasMes.D14 = objInformacionDashboardValidacion.DiasMes.D14;
                objInformacionDashboardValidacionDC.DiasMes.D15 = objInformacionDashboardValidacion.DiasMes.D15;
                objInformacionDashboardValidacionDC.DiasMes.D16 = objInformacionDashboardValidacion.DiasMes.D16;
                objInformacionDashboardValidacionDC.DiasMes.D17 = objInformacionDashboardValidacion.DiasMes.D17;
                objInformacionDashboardValidacionDC.DiasMes.D18 = objInformacionDashboardValidacion.DiasMes.D18;
                objInformacionDashboardValidacionDC.DiasMes.D19 = objInformacionDashboardValidacion.DiasMes.D19;
                objInformacionDashboardValidacionDC.DiasMes.D20 = objInformacionDashboardValidacion.DiasMes.D20;
                objInformacionDashboardValidacionDC.DiasMes.D21 = objInformacionDashboardValidacion.DiasMes.D21;
                objInformacionDashboardValidacionDC.DiasMes.D22 = objInformacionDashboardValidacion.DiasMes.D22;
                objInformacionDashboardValidacionDC.DiasMes.D23 = objInformacionDashboardValidacion.DiasMes.D23;
                objInformacionDashboardValidacionDC.DiasMes.D24 = objInformacionDashboardValidacion.DiasMes.D24;
                objInformacionDashboardValidacionDC.DiasMes.D25 = objInformacionDashboardValidacion.DiasMes.D25;
                objInformacionDashboardValidacionDC.DiasMes.D26 = objInformacionDashboardValidacion.DiasMes.D26;
                objInformacionDashboardValidacionDC.DiasMes.D27 = objInformacionDashboardValidacion.DiasMes.D27;
                objInformacionDashboardValidacionDC.DiasMes.D28 = objInformacionDashboardValidacion.DiasMes.D28;
                objInformacionDashboardValidacionDC.DiasMes.D29 = objInformacionDashboardValidacion.DiasMes.D29;
                objInformacionDashboardValidacionDC.DiasMes.D30 = objInformacionDashboardValidacion.DiasMes.D30;
                objInformacionDashboardValidacionDC.DiasMes.D31 = objInformacionDashboardValidacion.DiasMes.D31;

                lstInformacionDashboardValidacionCollectionDC.Add(objInformacionDashboardValidacionDC);
            }

            msgObtieneDashboardPreValidacionResponse.InformacionDashboardValidacion = lstInformacionDashboardValidacionCollectionDC;
            return msgObtieneDashboardPreValidacionResponse;
        }

        public override Abaseguros.Finanzas.SIAC.MessageContracts.ProcesaPreValidacionResponse ProcesaPreValidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ProcesaPreValidacionRequest request)
        {
            MessageContracts.ProcesaPreValidacionResponse msgProcesaPreValidacionResponse = new MessageContracts.ProcesaPreValidacionResponse();
            List<BusinessEntities.ProcesaPreValidacion> lstDashboardPreValidacion = new List<BusinessEntities.ProcesaPreValidacion>();
            msgProcesaPreValidacionResponse.Error = _objPreValidacionBL.ProcesaPreValidacion(request.Request_BU_Sistema_Plaza_FechaVal.BusinessUnit,
                                                                                            request.Request_BU_Sistema_Plaza_FechaVal.idSistema,
                                                                                            request.Request_BU_Sistema_Plaza_FechaVal.idPlaza,
                                                                                            request.Request_BU_Sistema_Plaza_FechaVal.FechaValidacion,
                                                                                            request.Login,
                                                                                            request.CargaRO);

            return msgProcesaPreValidacionResponse;
        }

        public override Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneResultadosPreValidacionResponse ObtieneResultadosPrevalidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneResultadosPreValidacionRequest request)
        {
            MessageContracts.ObtieneResultadosPreValidacionResponse msgObtieneResultadosPreValidacionResponse = new MessageContracts.ObtieneResultadosPreValidacionResponse();
            List<BusinessEntities.ResultadosPrePosValidacion> lstResultadosPrevalidacion = new List<BusinessEntities.ResultadosPrePosValidacion>();

            DataContracts.ResultadosPreValidacionDC objResultadosPreValidacionDC = null;
            DataContracts.ResultadosPreValidacionCollectionDC lstResultadosPreValidacionCollectionDC = new DataContracts.ResultadosPreValidacionCollectionDC();

            lstResultadosPrevalidacion = _objPreValidacionBL.ObtieneResultadosPreValidacion( request.Request_BU_Sistema_Plaza_FechaVal.BusinessUnit,
                                                                                            request.Request_BU_Sistema_Plaza_FechaVal.idSistema,
                                                                                            request.Request_BU_Sistema_Plaza_FechaVal.idPlaza,
                                                                                            request.Request_BU_Sistema_Plaza_FechaVal.FechaValidacion);
            foreach (BusinessEntities.ResultadosPrePosValidacion objResultadosPrevalidacion in lstResultadosPrevalidacion)
            {
                objResultadosPreValidacionDC = new DataContracts.ResultadosPreValidacionDC();
                objResultadosPreValidacionDC.ValidacionId = objResultadosPrevalidacion.ValidacionId;
                objResultadosPreValidacionDC.FechaContable = objResultadosPrevalidacion.FechaContable;
                objResultadosPreValidacionDC.Moneda = objResultadosPrevalidacion.Moneda;
                objResultadosPreValidacionDC.MontoContabilidad = objResultadosPrevalidacion.MontoContabilidad;
                objResultadosPreValidacionDC.MontoSistema = objResultadosPrevalidacion.MontoSistema;
                objResultadosPreValidacionDC.CuentaAlterna = objResultadosPrevalidacion.CuentaAlterna;
                objResultadosPreValidacionDC.Tolerancia = objResultadosPrevalidacion.Tolerancia;
                objResultadosPreValidacionDC.Estado = objResultadosPrevalidacion.Estado;
                objResultadosPreValidacionDC.Diferencia = objResultadosPrevalidacion.Diferencia;
                objResultadosPreValidacionDC.Comentarios = objResultadosPrevalidacion.Comentarios;
                objResultadosPreValidacionDC.HabilitaAplicaRevision = objResultadosPrevalidacion.HabilitaAplicaRevision;
                
                lstResultadosPreValidacionCollectionDC.Add(objResultadosPreValidacionDC);
            }

            msgObtieneResultadosPreValidacionResponse.ResultadosPreValidacionCollectionDC = lstResultadosPreValidacionCollectionDC;
            return msgObtieneResultadosPreValidacionResponse;
        }

        public override Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneResultadosPreValidacionResponse ObtieneHistorialPrevalidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneResultadosPreValidacionRequest request)
        {
            MessageContracts.ObtieneResultadosPreValidacionResponse msgObtieneResultadosPreValidacionResponse = new MessageContracts.ObtieneResultadosPreValidacionResponse();
            List<BusinessEntities.ResultadosPrePosValidacion> lstResultadosPrevalidacion = new List<BusinessEntities.ResultadosPrePosValidacion>();

            DataContracts.ResultadosPreValidacionDC objResultadosPreValidacionDC = null;
            DataContracts.ResultadosPreValidacionCollectionDC lstResultadosPreValidacionCollectionDC = new DataContracts.ResultadosPreValidacionCollectionDC();

            lstResultadosPrevalidacion = _objPreValidacionBL.ObtieneHistorialPreValidacion(  request.Request_BU_Sistema_Plaza_FechaVal.BusinessUnit,
                                                                                            request.Request_BU_Sistema_Plaza_FechaVal.idSistema,
                                                                                            request.Request_BU_Sistema_Plaza_FechaVal.idPlaza,
                                                                                            request.Request_BU_Sistema_Plaza_FechaVal.FechaValidacion);
            foreach (BusinessEntities.ResultadosPrePosValidacion objResultadosPrevalidacion in lstResultadosPrevalidacion)
            {
                objResultadosPreValidacionDC = new DataContracts.ResultadosPreValidacionDC();

                objResultadosPreValidacionDC.ValidacionId = objResultadosPrevalidacion.ValidacionId;
                objResultadosPreValidacionDC.RegistroId = objResultadosPrevalidacion.RegistroId;
                objResultadosPreValidacionDC.FechaContable = objResultadosPrevalidacion.FechaContable;
                objResultadosPreValidacionDC.Moneda = objResultadosPrevalidacion.Moneda;
                objResultadosPreValidacionDC.MontoContabilidad = objResultadosPrevalidacion.MontoContabilidad;
                objResultadosPreValidacionDC.MontoSistema = objResultadosPrevalidacion.MontoSistema;
                objResultadosPreValidacionDC.CuentaAlterna = objResultadosPrevalidacion.CuentaAlterna;
                objResultadosPreValidacionDC.Tolerancia = objResultadosPrevalidacion.Tolerancia;
                objResultadosPreValidacionDC.Estado = objResultadosPrevalidacion.Estado;
                objResultadosPreValidacionDC.Diferencia = objResultadosPrevalidacion.Diferencia;
                objResultadosPreValidacionDC.Comentarios = objResultadosPrevalidacion.Comentarios;

                lstResultadosPreValidacionCollectionDC.Add(objResultadosPreValidacionDC);
            }

            msgObtieneResultadosPreValidacionResponse.ResultadosPreValidacionCollectionDC = lstResultadosPreValidacionCollectionDC;
            return msgObtieneResultadosPreValidacionResponse;
        }

        public override Abaseguros.Finanzas.SIAC.MessageContracts.ActualizaResultadosPrevalidacionResponse ActualizaResultadosPrevalidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ActualizaResultadosPrevalidacionRequest request)
        {
            MessageContracts.ActualizaResultadosPrevalidacionResponse msgActualizaResultadosPreValidacionResponse = new MessageContracts.ActualizaResultadosPrevalidacionResponse();
            bool aceptado = false;
            bool rechazado = false;
            bool error = false;
            try
            {
                foreach (DataContracts.ActualizaPrevalidacionParametros par in request.Parametros)
                {
                    int resultado = _objPreValidacionBL.ActualizaResultadosPrevalidacion(par.ValidacionId, par.FechaContable,
                        par.CuentaAlterna, par.Moneda, par.Estado, par.Comentarios);
                    switch (resultado)
                    {
                        case 1:
                            aceptado = true;
                            rechazado = false;
                            break;
                        case 2:
                            aceptado = false;
                            rechazado = true;
                            break;
                        default:
                            break;
                    }
                }
            }
            catch
            {
                error = true;
            }

            if (error)
            {
                msgActualizaResultadosPreValidacionResponse.Error = "Error al actualizar los datos, favor de internarlo más tarde";
            }
            else
            {
                if (rechazado)
                {
                    msgActualizaResultadosPreValidacionResponse.Error = "Prevalidación rechazada, para enviar la información contable se deberá generar y prevalidar nuevamente";
                }
                else
                {
                    if (aceptado)
                    {
                        msgActualizaResultadosPreValidacionResponse.Error = "Prevalidación confirmada, se enviará la información contable en la siguiente transmisión";
                    }
                }
            }
            
            return msgActualizaResultadosPreValidacionResponse;
        }

        public override MessageContracts.FechasAcumuladoSiniestros ObtieneAcumuladoSiniestros()
        {
            BusinessEntities.RangoFechas rango = _objPreValidacionBL.ObtieneFechasAcumuladoSiniestros();
            MessageContracts.FechasAcumuladoSiniestros fechas = new MessageContracts.FechasAcumuladoSiniestros();
            fechas.FechaInicial = rango.FechaInicial;
            fechas.FechaFinal = rango.FechaFinal;
            return fechas;
        }
    }

}

