//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.ServiceImplementation
{
    /// <summary>
    /// Service Class - ReportesOperativosService
    /// </summary>
    [WCF::ServiceBehavior(Name = "ReportesOperativosService",
        Namespace = "http://abaseguros.com",
        InstanceContextMode = WCF::InstanceContextMode.PerSession,
        ConcurrencyMode = WCF::ConcurrencyMode.Single)]
    public abstract class ReportesOperativosServiceBase : Abaseguros.Finanzas.SIAC.ServiceContracts.IReportesOperativosServiceContract
    {
        #region ReportesOperativosServiceContract Members

        public virtual Abaseguros.Finanzas.SIAC.MessageContracts.HistorialROResponse ObtieneHistorialRO(Abaseguros.Finanzas.SIAC.MessageContracts.HistorialRORequest request)
        {
            return null;
        }

        public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ParametroReporteResponse InsertaParametroReporte(Abaseguros.Finanzas.SIAC.MessageContracts.ParametroReporteRequest request)
        {
            return null;
        }

        #endregion
    }

    public partial class ReportesOperativosService : ReportesOperativosServiceBase
    {
        BusinessLogic.ReportesOperativosBL _objReportesOperativosBL = new BusinessLogic.ReportesOperativosBL();

        public override Abaseguros.Finanzas.SIAC.MessageContracts.HistorialROResponse ObtieneHistorialRO(Abaseguros.Finanzas.SIAC.MessageContracts.HistorialRORequest request)
        {
            MessageContracts.HistorialROResponse objHistorialROResponse = new MessageContracts.HistorialROResponse();
            DataContracts.HistorialROCollectionDC objHistorialROCollectionDC = new DataContracts.HistorialROCollectionDC();
            DataContracts.HistorialRODC objHistorialRODC = new DataContracts.HistorialRODC();
            List<BusinessEntities.HistorialRO> listaHistorial = new List<BusinessEntities.HistorialRO>();
            listaHistorial = _objReportesOperativosBL.obtieneHistorialRO(request.FechaValidacion);
            foreach (Abaseguros.Finanzas.SIAC.BusinessEntities.HistorialRO hist in listaHistorial)
            {
                objHistorialRODC = new DataContracts.HistorialRODC()
                {
                    idRutasArchivos = hist.idRutasArchivos,
                    TipoArchivo = hist.TipoArchivo,
                    Nombre = hist.Nombre,
                    Plaza = hist.Plaza,
                    Sistema = hist.Sistema,
                    Usuario = hist.Usuario,
                    FechaModificacion = hist.FechaModificacion,
                    Estatus = hist.Estatus
                };
                objHistorialROCollectionDC.Add(objHistorialRODC);
            }
            objHistorialROResponse.HistorialRO = objHistorialROCollectionDC;
            return objHistorialROResponse;
        }

        public override Abaseguros.Finanzas.SIAC.MessageContracts.ParametroReporteResponse InsertaParametroReporte(MessageContracts.ParametroReporteRequest parametroReporte)
        {
            BusinessEntities.InsertaParametroReporte objInsertaParametroReporte = new BusinessEntities.InsertaParametroReporte();
            MessageContracts.ParametroReporteResponse objParametroReporteResponse = new MessageContracts.ParametroReporteResponse();

            objInsertaParametroReporte.IdRutaArchivos = parametroReporte.InsertaParametroReporte.idRutaArchivos;
            objInsertaParametroReporte.BusinessUnit = parametroReporte.InsertaParametroReporte.BusinessUnit;
            objInsertaParametroReporte.IdPlaza = parametroReporte.InsertaParametroReporte.idPlaza;
            objInsertaParametroReporte.IdSistema = parametroReporte.InsertaParametroReporte.idSistema;
            objInsertaParametroReporte.FechaValidacion = parametroReporte.InsertaParametroReporte.FechaValidacion;
            objInsertaParametroReporte.Login = parametroReporte.InsertaParametroReporte.Login;

            objParametroReporteResponse.idSesion = _objReportesOperativosBL.InsertaParametroReporte(objInsertaParametroReporte);
            return objParametroReporteResponse;
        }
    }

}

