//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Abaseguros.Finanzas.SIAC.DataContracts;
using Abaseguros.Finanzas.SIAC.MessageContracts;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.ServiceImplementation
{	
	/// <summary>
	/// Service Class - ValidacionesSiacService
	/// </summary>
	[WCF::ServiceBehavior(Name = "ValidacionesSiacService", 
		Namespace = "http://abaseguros.com", 
		InstanceContextMode = WCF::InstanceContextMode.PerSession, 
		ConcurrencyMode = WCF::ConcurrencyMode.Single )]
	public abstract class ValidacionesSiacServiceBase : Abaseguros.Finanzas.SIAC.ServiceContracts.IValidacionesSiacServiceContract
	{
		#region ValidacionesSiacServiceContract Members

		public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneBitacoraResponse ObtieneBitacora(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneBitacoraRequest request)
		{
			return null;
		}

		public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneBitacoraHistorialResponse ObtieneBitacoraHistorial(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneBitacoraRequest request)
		{
			return null;
		}

        public virtual Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneBitacoraResponse ObtieneBitacoraCargaReporte(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneBitacoraReporteRequest request)
        {
            return null;
        }

	    public virtual Abaseguros.Finanzas.SIAC.MessageContracts.GetJournalValidationResponse GetJournalValidation(Abaseguros.Finanzas.SIAC.MessageContracts.GetJournalValidationRequest request)
	    {
	        return null;
	    }

	    #endregion
	}

    public partial class ValidacionesSiacService : ValidacionesSiacServiceBase
    {
        BusinessLogic.ValidacionSiacBL _objValidacionSiacBL = new BusinessLogic.ValidacionSiacBL();

        public  override Abaseguros.Finanzas.SIAC.MessageContracts.GetJournalValidationResponse GetJournalValidation(
            Abaseguros.Finanzas.SIAC.MessageContracts.GetJournalValidationRequest request)
        {
            MessageContracts.GetJournalValidationResponse objGetJournalValidationResponse = new MessageContracts.GetJournalValidationResponse();
            List<BusinessEntities.GetJournalValidation> lstGetJournalValidations = null;

            DataContracts.GetJournalValidationCollectionDC lstGetJournalValidationDc = new DataContracts.GetJournalValidationCollectionDC();
            DataContracts.GetJournalValidationDC objGetJournalValidationDc = null;

            lstGetJournalValidations = _objValidacionSiacBL.GetJournalValidation(request.XmlJournal);

            foreach (BusinessEntities.GetJournalValidation objGetJournalValidation in lstGetJournalValidations)
            {
                objGetJournalValidationDc = new DataContracts.GetJournalValidationDC();
                //objGetJournalValidationDc.XmlJournal = objGetJournalValidation.XmlJournal;

                lstGetJournalValidationDc.Add(objGetJournalValidationDc);
            }

            objGetJournalValidationResponse.GetJournalValidation = lstGetJournalValidationDc;

            return objGetJournalValidationResponse;
        }
        public override Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneBitacoraResponse ObtieneBitacora(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneBitacoraRequest request)
        {
            MessageContracts.ObtieneBitacoraResponse objObtieneBitacoraResponse = new MessageContracts.ObtieneBitacoraResponse();
            List<BusinessEntities.ObtieneBitacora> lstObtieneBitacora = null;

            DataContracts.ObtieneBitacoraCollectionDC lstObtieneBitacoraCollectionDC = new DataContracts.ObtieneBitacoraCollectionDC();
            DataContracts.ObtieneBitacoraDC objObtieneBitacoraDC = null;


            lstObtieneBitacora = _objValidacionSiacBL.ObtieneBitacora(request.idTipoValidacion,
                                                                        request.Request_BU_Sistema_Plaza_FechaVal.BusinessUnit,
                                                                        request.Request_BU_Sistema_Plaza_FechaVal.idSistema,
                                                                        request.Request_BU_Sistema_Plaza_FechaVal.idPlaza,
                                                                        request.Request_BU_Sistema_Plaza_FechaVal.FechaValidacion);

            foreach (BusinessEntities.ObtieneBitacora objObtieneBitacora in lstObtieneBitacora)
            {
                objObtieneBitacoraDC = new DataContracts.ObtieneBitacoraDC();
                objObtieneBitacoraDC.idMensaje = objObtieneBitacora.idMensaje;
                objObtieneBitacoraDC.FechaModificacion = objObtieneBitacora.FechaModificacion;
                objObtieneBitacoraDC.Mensaje = objObtieneBitacora.Mensaje;
                objObtieneBitacoraDC.Estado = objObtieneBitacora.Estado;

                lstObtieneBitacoraCollectionDC.Add(objObtieneBitacoraDC);
            }

            objObtieneBitacoraResponse.ObtieneBitacora = lstObtieneBitacoraCollectionDC;

            return objObtieneBitacoraResponse;
        }

        public override Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneBitacoraHistorialResponse ObtieneBitacoraHistorial(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneBitacoraRequest request)
        {
            MessageContracts.ObtieneBitacoraHistorialResponse objObtieneBitacoraHistorialResponse = new MessageContracts.ObtieneBitacoraHistorialResponse();
            List<BusinessEntities.ObtieneBitacoraHistorial> lstObtieneBitacoraHistorial = null;

            DataContracts.ObtieneBitacoraCollectionDC lstObtieneBitacoraCollectionDC = new DataContracts.ObtieneBitacoraCollectionDC();
            DataContracts.ObtieneBitacoraDC objObtieneBitacoraDC = null;

            lstObtieneBitacoraHistorial = _objValidacionSiacBL.ObtieneBitacoraHistorial(request.idTipoValidacion,
                                                                        request.Request_BU_Sistema_Plaza_FechaVal.BusinessUnit,
                                                                        request.Request_BU_Sistema_Plaza_FechaVal.idSistema,
                                                                        request.Request_BU_Sistema_Plaza_FechaVal.idPlaza,
                                                                        request.Request_BU_Sistema_Plaza_FechaVal.FechaValidacion);

            foreach (BusinessEntities.ObtieneBitacoraHistorial objObtieneBitacoraHistorial in lstObtieneBitacoraHistorial)
            {
                objObtieneBitacoraDC = new DataContracts.ObtieneBitacoraDC();
                objObtieneBitacoraDC.idMensaje = objObtieneBitacoraHistorial.ObtieneBitacora.idMensaje;
                objObtieneBitacoraDC.FechaModificacion = objObtieneBitacoraHistorial.ObtieneBitacora.FechaModificacion;
                objObtieneBitacoraDC.Mensaje = objObtieneBitacoraHistorial.ObtieneBitacora.Mensaje;
                objObtieneBitacoraDC.Estado = objObtieneBitacoraHistorial.ObtieneBitacora.Estado;
                objObtieneBitacoraDC.idValidacion = objObtieneBitacoraHistorial.IdValidacion;

                lstObtieneBitacoraCollectionDC.Add(objObtieneBitacoraDC);
            }

            objObtieneBitacoraHistorialResponse.ObtieneBitacora = lstObtieneBitacoraCollectionDC;

            return objObtieneBitacoraHistorialResponse;
        }

        public override Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneBitacoraResponse ObtieneBitacoraCargaReporte(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneBitacoraReporteRequest request)
        {
            MessageContracts.ObtieneBitacoraResponse objObtieneBitacoraResponse = new MessageContracts.ObtieneBitacoraResponse();
            List<BusinessEntities.ObtieneBitacora> lstObtieneBitacora = null;

            DataContracts.ObtieneBitacoraCollectionDC lstObtieneBitacoraCollectionDC = new DataContracts.ObtieneBitacoraCollectionDC();
            DataContracts.ObtieneBitacoraDC objObtieneBitacoraDC = null;


            lstObtieneBitacora = _objValidacionSiacBL.ObtieneBitacoraCargaReporte(request.BusinessUnit,
                                                                        request.TipoArchivo,
                                                                        request.TipoValidacion,
                                                                        request.Fecha,
                                                                        request.Usuario);

            foreach (BusinessEntities.ObtieneBitacora objObtieneBitacora in lstObtieneBitacora)
            {
                objObtieneBitacoraDC = new DataContracts.ObtieneBitacoraDC();
                objObtieneBitacoraDC.idMensaje = objObtieneBitacora.idMensaje;
                objObtieneBitacoraDC.FechaModificacion = objObtieneBitacora.FechaModificacion;
                objObtieneBitacoraDC.Mensaje = objObtieneBitacora.Mensaje;
                objObtieneBitacoraDC.Estado = objObtieneBitacora.Estado;

                lstObtieneBitacoraCollectionDC.Add(objObtieneBitacoraDC);
            }

            objObtieneBitacoraResponse.ObtieneBitacora = lstObtieneBitacoraCollectionDC;

            return objObtieneBitacoraResponse;
        }
    }
	
}

