//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.ServiceContracts
{
	/// <summary>
	/// Service Contract Class - MonitoreoPCWServiceContract
	/// </summary>
	[WCF::ServiceContract(Namespace = "http://abaseguros.com", Name = "MonitoreoPCWServiceContract", SessionMode = WCF::SessionMode.Allowed, ProtectionLevel = ProtectionLevel.None )]
	public partial interface IMonitoreoPCWServiceContract 
	{
		[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "ObtieneDashboardMonitoreoPCW", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardMonitoreoPCWResponse ObtieneDashboardMonitoreoPCW(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardMonitoreoPCWRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "ObtieneReporteMonitoreoPCW", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteMonitoreoPCWResponse ObtieneReporteMonitoreoPCW(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteMonitoreoPCWRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "ObtieneReporteCalendarioPCW", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteCalendarioPCWResponse ObtieneReporteCalendarioPCW(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteCalendarioPCWRequest request);
		
	}
}

