//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.ServiceContracts
{
	/// <summary>
	/// Service Contract Class - MonitoreoPSServiceContract
	/// </summary>
	[WCF::ServiceContract(Namespace = "http://abaseguros.com", Name = "MonitoreoPSServiceContract", SessionMode = WCF::SessionMode.Allowed, ProtectionLevel = ProtectionLevel.None )]
	public partial interface IMonitoreoPSServiceContract 
	{
		[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "ObtieneDashboardMonitoreoPS", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardMonitoreoPSResponse ObtieneDashboardMonitoreoPS(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardMonitoreoPSRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "ObtieneReporteMonitoreoPS", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteMonitoreoPSResponse ObtieneReporteMonitoreoPS(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneReporteMonitoreoPSRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "ObtenerReporteDeSeguimientoValoresIniciales", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ObtenerReporteDeSeguimientoValoresInicialesResponse ObtenerReporteDeSeguimientoValoresIniciales(Abaseguros.Finanzas.SIAC.MessageContracts.ObtenerReporteDeSeguimientoValoresInicialesRequest request);
		
	}
}

