//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.ServiceContracts
{
	/// <summary>
	/// Service Contract Class - PosValidacionServiceContract
	/// </summary>
	[WCF::ServiceContract(Namespace = "http://abaseguros.com", Name = "PosValidacionServiceContract", SessionMode = WCF::SessionMode.Allowed, ProtectionLevel = ProtectionLevel.None )]
	public partial interface IPosValidacionServiceContract 
	{
		[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "ObtieneDashboardPosValidacion", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardPosValidacionResponse ObtieneDashboardPosValidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardPosValidacionRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "InsertarReportePosValidacion", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.InsertaReportePorValidacionResponse InsertarReportePosValidacion(Abaseguros.Finanzas.SIAC.MessageContracts.InsertarReportePosValidacionRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "ObtieneResultadoPosValidacion", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ResultadoPosValidacionResponse ObtieneResultadoPosValidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ResultadoPosValidacionRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "ObtieneHistorialPosValidacion", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ResultadoPosValidacionResponse ObtieneHistorialPosValidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ResultadoPosValidacionRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://abaseguros.com/PosValidacionServiceContract/ProcesaPosValidacion", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ProcesaPosValidacionResponse ProcesaPosValidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ProcesaPosValidacionRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "ActualizaResultadosPosvalidacion", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ActualizaResultadosPosvalidacionResponse ActualizaResultadosPosvalidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ActualizaResultadosPosvalidacionRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "ObtieneMensajesReportePosValidacion", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneMensajesReportePosValidacionResponse ObtieneMensajesReportePosValidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneMensajesReportePosValidacionRequest request);
		
	}
}

