//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;
using WCF = global::System.ServiceModel;

namespace Abaseguros.Finanzas.SIAC.ServiceContracts
{
	/// <summary>
	/// Service Contract Class - PreValidacionServiceContract
	/// </summary>
	[WCF::ServiceContract(Namespace = "http://abaseguros.com", Name = "PreValidacionServiceContract", SessionMode = WCF::SessionMode.Allowed, ProtectionLevel = ProtectionLevel.None )]
	public partial interface IPreValidacionServiceContract 
	{
		[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "ObtieneDashboardPreValidacion", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardPreValidacionResponse ObtieneDashboardPreValidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneDashboardPreValidacionRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://abaseguros.com/PreValidacionServiceContract/ProcesaPreValidacion", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ProcesaPreValidacionResponse ProcesaPreValidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ProcesaPreValidacionRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "ObtieneResultadosPrevalidacion", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneResultadosPreValidacionResponse ObtieneResultadosPrevalidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneResultadosPreValidacionRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "http://abaseguros.com/PreValidacionServiceContract/ObtieneHistorialPrevalidacion", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneResultadosPreValidacionResponse ObtieneHistorialPrevalidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ObtieneResultadosPreValidacionRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "ActualizaResultadosPrevalidacion", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.ActualizaResultadosPrevalidacionResponse ActualizaResultadosPrevalidacion(Abaseguros.Finanzas.SIAC.MessageContracts.ActualizaResultadosPrevalidacionRequest request);
		
[WCF::OperationContract(IsTerminating = false, IsInitiating = true, IsOneWay = false, AsyncPattern = false, Action = "ObtieneAcumuladoSiniestros", ProtectionLevel = ProtectionLevel.None)]
		Abaseguros.Finanzas.SIAC.MessageContracts.FechasAcumuladoSiniestros ObtieneAcumuladoSiniestros();
		
	}
}

